$statusMarkers = @(
    "check_pdf_dependency_inputs.ps1",
    "featherdoc.pdf_dependency_inputs_check.v1",
    "blocking_checks = []",
    "blocking_summary.blocking_check_count = 0",
    "memory_guard_blocked = false",
    "memory_guard_skipped = false",
    "workstation_free_memory_available",
    "git status --short",
    "free_memory_mb",
    "min_free_memory_mb",
    "memory guard blocked=false",
    "memory guard skipped=false",
    "free memory MB",
    "minimum free memory MB",
    "2026-05-20",
    "2026-05-24",
    "2026-05-25",
    "2026-05-26",
    "2026-05-27",
    "2026-05-26T22:50:00",
    "FinalizeOnly",
    "release_blocker_count = 0",
    "action_item_count = 0",
    "build_dir_source = requested",
    "build_dir_auto_candidates",
    "pdf_build_options",
    "looks_reusable",
    "preflight_ready = true",
    "preflight governance report",
    "raw summary",
    "full_visual_gate_required = true",
    "full_visual_gate_status = not_run_by_preflight_governance",
    "preflight-governance",
    "full gate summary",
    "contact sheet",
    "evidence_kind",
    "synthetic_fixture",
    "synthetic_preflight_evidence",
    "release_ready = true",
    "not_run_by_preflight_governance",
    "evidence_kind = real_build",
    "controlled_visual_smoke_status = pass",
    "controlled_visual_smoke_passed = true",
    "status = ready",
    "status = pass",
    "verdict = pass",
    "finalize_only = true",
    "skip_preflight = true",
    "output_gap_count = 0",
    "missing_output_count = 0",
    "visual_baseline_manifest_count = 42",
    "baselines_count = 44",
    "cjk_manifest_count = 43",
    "cjk_copy_search_count = 43",
    "generated_at = 2026-05-25T07:13:30",
    "generated_at = 2026-05-25T07:15:13",
    "generated_at = 2026-05-26T23:19:01",
    "generated_at = 2026-05-27T01:38:37",
    "2026-05-28",
    "generated_at = 2026-05-28T14:35:38",
    "generated_at = 2026-05-28T14:38:22",
    "generated_at = 2026-05-28T14:38:23",
    "generated_at = 2026-05-28T14:49:37",
    "generated_at = 2026-05-28T14:38:33",
    "status = pass",
    "verdict = pass",
    "full_visual_gate_status = pass",
    "outer_guard_status = completed",
    "outer_guard_timed_out = false",
    "full_summary_fresh_for_attempt = true",
    "passed_stage_count = 6",
    "failed_stage_count = 0",
    "incomplete_stage_count = 0",
    "visual_baseline_fresh_rendered_count = 44",
    "visual_baseline_fresh_missing_sample_count = 0",
    "aggregate_contact_sheet_status = pass",
    "summary_detail_payload_included = true",
    "summary_detail_status = complete",
    "core_pass_written_before_detail_payload",
    "visual_full_gate_status = pass",
    "visual_full_gate_full_visual_gate_status = pass",
    "visual_full_gate_outer_guard_status = completed",
    "visual_full_gate_attempt_summary_full_visual_gate_status = pass",
    "visual_gate_release_evidence_accepted = true",
    "execution_status = pass",
    "free_memory_mb = 4061.3",
    "output/pdf-visual-release-gate-preflight-current/summary.json",
    "pdf_preflight_default_current_summary_trace",
    "blocking_check_count = 0",
    "blocking_checks = []",
    "free_memory_mb = 2691.4",
    "-FinalizeOnly -SkipPreflight",
    "selected_pdfium_provider = prebuilt",
    "pdf_dependency_inputs_status = ready",
    "pdf_dependency_missing_input_count = 0",
    "pdf_build_options_enabled = true",
    "pdfio_dependency_ready = true",
    "pdfium_dependency_ready = true",
    "visual_baseline_sample_count = 42",
    "missing_visual_baseline_pdf_count = 0",
    "cjk_text_layer_sample_count = 43",
    "missing_cjk_text_layer_pdf_count = 0",
    "ctest_list_contains_pdf_gate_tests = pass",
    "run_pdf_ctest_bounded_subset.ps1",
    "pdf_bounded_ctest",
    "pdf_bounded_ctest_summary_count",
    "pdf_bounded_ctest_pass_count",
    "pdf_bounded_ctest_skipped_test_count",
    "pdf_bounded_ctest_selected_test_count",
    "pdf_bounded_ctest_subsets",
    "pdf_bounded_ctest_summary_json_display",
    "pdf_bounded_ctest_governance_trace",
    "pdf_bounded_ctest_source_report_block_trace",
    "pdf_visual_gate_rollup_material_safety_trace",
    "write_pdf_visual_gate_attempt_summary.ps1",
    "featherdoc.pdf_visual_gate_attempt_summary.v1",
    "attempt-summary.json",
    "pdf_visual_gate_attempt_status",
    "pdf_visual_gate_attempt_verdict",
    "pdf_visual_gate_attempt_full_visual_gate_status",
    "pdf_visual_gate_attempt_evidence_scope",
    "bounded_attempt_auxiliary_only",
    "pdf_visual_gate_attempt_outer_guard_status",
    "pdf_visual_gate_attempt_outer_guard_timed_out",
    "pdf_visual_gate_attempt_outer_guard_timeout_seconds",
    "outer_guard_status = timed_out",
    "outer_guard_timed_out = true",
    "outer_guard_timeout_seconds = 60",
    "pdf_visual_gate_attempt_outer_guard_trace",
    "pdf_visual_gate_attempt_pdf_regression_skipped_test_count",
    "pdf_visual_gate_attempt_visual_baseline_render_status",
    "pdf_visual_gate_attempt_summary_trace",
    "pdf_visual_gate_attempt_governance_trace",
    "pdf_visual_gate_attempt_material_safety_trace",
    "pdf_visual_gate_attempt_rollup_material_safety_trace",
    "pdf_visual_gate_attempt_final_review_material_safety_trace",
    "run_pdf_visual_full_gate_guarded.ps1",
    "featherdoc.pdf_visual_full_gate_guarded_summary.v1",
    "visual_full_gate_attempt_passed_stage_count",
    "visual_full_gate_attempt_visual_baseline_fresh_rendered_count",
    "visual_full_gate_attempt_aggregate_contact_sheet_status",
    "visual_full_gate_pass_summary_before_outer_timeout",
    "visual_gate_pass_summary_before_outer_timeout",
    "pass_summary_before_outer_timeout",
    "timed_out_after_pass_summary",
    "pdf_visual_gate_core_pass_summary_trace",
    "summary_detail_payload_included",
    "summary_detail_status",
    "core_pass_written_before_detail_payload",
    "--skip-contact-sheet",
    "contact_sheet_skipped",
    "pdf_visual_full_gate_guarded_summary_trace",
    "featherdoc.pdf_visual_baseline_slice.v1",
    "VisualBaselineSliceOnly",
    "VisualBaselineOffset",
    "VisualBaselineLimit",
    "visual_baseline_slice_only",
    "slice_summary_does_not_replace_full_visual_gate_verdict",
    "pdf_visual_baseline_slice_summary_trace",
    "featherdoc.pdf_visual_aggregate_contact_sheet_rebuild.v1",
    "RebuildAggregateContactSheetOnly",
    "aggregate_contact_sheet_rebuild_only",
    "aggregate_rebuild_summary_does_not_replace_full_visual_gate_verdict",
    "aggregate-contact-sheet-rebuild-summary.json",
    "pdf_visual_aggregate_contact_sheet_rebuild_trace",
    "pdf_visual_gate_core_pass_summary_trace",
    "summary_detail_payload_included",
    "summary_detail_status",
    "core_pass_written_before_detail_payload",
    "--skip-contact-sheet",
    "contact_sheet_skipped",
    "run_pdf_visual_segmented_resume.ps1",
    "featherdoc.pdf_visual_segmented_resume_summary.v1",
    "segmented-resume-summary.json",
    "visual_segmented_resume_auxiliary_only",
    "resume_tail_fully_planned",
    "segmented_resume_does_not_replace_full_visual_gate_verdict",
    "pdf_visual_segmented_resume_summary_trace",
    "write_pdf_visual_segmented_gate_summary.ps1",
    "featherdoc.pdf_visual_segmented_gate_summary.v1",
    "segmented-summary.json",
    "status",
    "verdict",
    "pdf_visual_segmented_gate_status",
    "pdf_visual_segmented_gate_verdict",
    "pdf_visual_segmented_gate_full_visual_gate_status",
    "pdf_visual_segmented_gate_evidence_scope",
    "segmented_visual_gate_auxiliary_only",
    "pdf_visual_segmented_gate_boundary",
    "segmented_summary_does_not_replace_full_visual_gate_verdict",
    "pdf_visual_segmented_gate_summary_json_display",
    "pdf_visual_segmented_gate_slice_summary_count",
    "pdf_visual_segmented_gate_slice_pass_count",
    "pdf_visual_segmented_gate_slice_failed_count",
    "pdf_visual_segmented_gate_covered_baseline_count",
    "pdf_visual_segmented_gate_expected_visual_render_count",
    "pdf_visual_segmented_gate_attempt_stage_count",
    "pdf_visual_segmented_gate_attempt_passed_stage_count",
    "pdf_visual_segmented_gate_visual_baseline_render_status",
    "pdf_visual_segmented_gate_aggregate_contact_sheet_status",
    "pdf_visual_segmented_gate_aggregate_contact_sheet_display",
    "pdf_visual_segmented_gate_aggregate_contact_sheet_bytes",
    "pdf_visual_segmented_gate_aggregate_rebuild_status",
    "pdf_visual_segmented_gate_aggregate_rebuild_selected_baseline_count",
    "pdf_visual_segmented_gate_summary_trace",
    "pdf_visual_segmented_gate_governance_trace",
    "pdf_visual_segmented_gate_material_safety_trace",
    "pdf_visual_segmented_gate_rollup_material_safety_trace",
    "pdf_visual_segmented_gate_final_review_material_safety_trace",
    "pdf_ctest_bounded_subset_release_trace",
    "pdf_ctest_bounded_contract_static_release_trace",
    "pdf_ctest_bounded_cjk_flow_static_release_trace",
    "pdf_ctest_bounded_regression_basic_text_release_trace",
    "pdf_ctest_bounded_regression_styled_document_release_trace",
    "pdf_ctest_bounded_regression_business_samples_release_trace",
    "pdf_ctest_bounded_regression_table_layout_release_trace",
    "Subset",
    "subset = smoke-import",
    "subset = contract-static",
    "subset = cjk-flow-static",
    "subset = regression-basic-text",
    "subset = regression-styled-document",
    "subset = regression-business-samples",
    "subset = regression-table-layout",
    "contract-static",
    "cjk-flow-static",
    "regression-basic-text",
    "regression-styled-document",
    "regression-business-samples",
    "regression-table-layout",
    "selected_test_count = 10",
    "skipped_test_count = 0",
    "ctest_timeout_seconds = 60",
    "pdf_cjk_font_search_density_flow_contract",
    "pdf_cjk_list_page_flow_contract",
    "pdf_regression_manifest",
    "pdf_regression_four-page-text",
    "pdf_regression_styled-text",
    "pdf_regression_document-font-matrix-text",
    "pdf_regression_invoice-grid-text",
    "pdf_regression_document-cjk-image-wrap-stress-text",
    "pdf_regression_document-table-merged-header-footer-variants-text",
    "skipped",
    "***Skipped",
    "912x14566",
    "1822428",
    "pdfium_ready = true",
    "pdfium_prebuilt_root_exists = true",
    "TinaToolBox\dependencies\pdfium-win-x64",
    "lib\pdfium.dll.lib",
    "include\fpdfview.h",
    "bin\pdfium.dll",
    "missing_input_count = 1",
    "tmp\pdfio-src\pdfio.h",
    "output_gap_count = 3",
    ".bpdf-roundtrip-msvc",
    "CMakeCache.txt",
    "CTestTestfile.cmake",
    "FEATHERDOC_BUILD_PDF=ON",
    "FEATHERDOC_BUILD_PDF_IMPORT=ON",
    "pdf_build_options_enabled",
    "out\build",
    "-MinFreeMemoryMB",
    "-SkipMemoryGuard",
    "missing_output_count = 87",
    "aggregate-contact-sheet.png",
    "fake-pdf-build",
    "fake ctest",
    "fake python",
    "fake / synthetic",
    "test fixture",
    "reusable release build substitute",
    "pdf_dependency_inputs",
    "pdf_dependency_inputs_status",
    "pdf_dependency_missing_input_count",
    "pdfio_dependency_ready",
    "pdfium_dependency_ready",
    "run_pdf_visual_release_gate.ps1"
)
