#if defined(FEATHERDOC_ENABLE_PDF_FONT_SUBSET)
#include <featherdoc/pdf/pdf_font_subset.hpp>
#endif
#include <featherdoc/pdf/pdf_text_metrics.hpp>
#include <featherdoc/pdf/pdf_writer.hpp>

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <string_view>
#include <tuple>
#include <utility>
#include <vector>

#include <ft2build.h>
#include FT_FREETYPE_H

extern "C" {
#include <pdfio-content.h>
#include <pdfio.h>
}

namespace featherdoc::pdf {
namespace {

#include "pdf_writer_resources.inc"
#include "pdf_writer_font_objects.inc"
#include "pdf_writer_text_content.inc"
#include "pdf_writer_page_content.inc"

} // namespace

PdfDocumentLayout make_pdfio_probe_layout(const PdfWriterOptions &options) {
    PdfDocumentLayout layout;
    layout.metadata.title = options.title;
    layout.metadata.creator = options.creator;

    PdfPageLayout page;
    page.size = options.page_size;

    const double width = std::max(page.size.width_points, 144.0);
    const double height = std::max(page.size.height_points, 144.0);

    page.rectangles.push_back(PdfRectangle{
        PdfRect{36.0, 36.0, width - 72.0, height - 72.0},
        PdfRgbColor{0.12, 0.16, 0.22},
        PdfRgbColor{1.0, 1.0, 1.0},
        1.0,
        true,
        false,
    });

    page.text_runs.push_back(PdfTextRun{
        PdfPoint{72.0, height - 96.0},
        options.title,
        "Helvetica",
        {},
        18.0,
        PdfRgbColor{0.0, 0.0, 0.0},
        false,
        false,
        false,
        false,
    });
    page.text_runs.push_back(PdfTextRun{
        PdfPoint{72.0, height - 120.0},
        "Generated by the FeatherDoc IPdfGenerator/PDFio prototype.",
        "Helvetica",
        {},
        10.0,
        PdfRgbColor{0.0, 0.0, 0.0},
        false,
        false,
        false,
        false,
    });

    layout.pages.push_back(std::move(page));
    return layout;
}

PdfWriteResult write_pdfio_document(const std::filesystem::path &output_path,
                                    const PdfDocumentLayout &layout,
                                    const PdfWriterOptions &options) {
    PdfioErrorState error_state;
    PdfWriteResult result;
    if (layout.pages.empty()) {
        result.error_message = "PDF layout does not contain any pages";
        return result;
    }

    ImageSourceCleanup image_cleanup;
    for (const auto &page : layout.pages) {
        for (const auto &image : page.images) {
            if (image.cleanup_source_after_write) {
                image_cleanup.paths.push_back(image.source_path);
            }
        }
    }

    const auto output_string = output_path.string();
    const PdfPageSize first_page_size = layout.pages.front().size;
    pdfio_rect_t media_box{0.0, 0.0, first_page_size.width_points,
                           first_page_size.height_points};

    std::unique_ptr<pdfio_file_t, PdfioFileCloser> pdf(
        pdfioFileCreate(output_string.c_str(), "1.7", &media_box, &media_box,
                        pdfio_error_callback, &error_state));
    if (!pdf) {
        result.error_message =
            build_error("Unable to create PDF file", error_state);
        return result;
    }

    const std::string creator = layout.metadata.creator.empty()
                                    ? options.creator
                                    : layout.metadata.creator;
    const std::string title =
        layout.metadata.title.empty() ? options.title : layout.metadata.title;

    pdfioFileSetCreator(pdf.get(), creator.c_str());
    pdfioFileSetTitle(pdf.get(), title.c_str());

    FontSubsetStorage font_subset_storage;
    for (const auto &page : layout.pages) {
        std::string page_error;
        if (!write_probe_page(pdf.get(), page, options, font_subset_storage,
                              page_error)) {
            result.error_message = build_error(page_error, error_state);
            return result;
        }
    }

    if (!pdfioFileClose(pdf.release())) {
        result.error_message =
            build_error("Unable to close PDF file", error_state);
        return result;
    }

    result.success = true;
    if (std::filesystem::exists(output_path)) {
        result.bytes_written = std::filesystem::file_size(output_path);
    }
    return result;
}

PdfWriteResult PdfioGenerator::write(const PdfDocumentLayout &layout,
                                     const std::filesystem::path &output_path,
                                     const PdfWriterOptions &options) {
    return write_pdfio_document(output_path, layout, options);
}

PdfWriteResult
write_pdfio_probe_document(const std::filesystem::path &output_path,
                           const PdfWriterOptions &options) {
    PdfioGenerator generator;
    return generator.write(make_pdfio_probe_layout(options), output_path,
                           options);
}

} // namespace featherdoc::pdf
