#pragma once

#include <cstdint>

namespace featherdoc {

class Document;
class Paragraph;
class Run;
class Table;
class TableCell;
class TableRow;
class TemplatePart;

struct body_block_inspection_summary;
struct bookmark_block_visibility_binding;
struct bookmark_block_visibility_result;
struct bookmark_fill_result;
struct bookmark_summary;
struct bookmark_text_binding;
struct border_inspection_summary;
struct caption_field_options;
struct character_style_definition;
struct comment_metadata_update;
struct complex_field_instruction_fragment;
struct complex_field_options;
struct content_control_form_state_options;
struct content_control_list_item;
struct content_control_summary;
struct custom_xml_data_binding_sync_issue;
struct custom_xml_data_binding_sync_item;
struct custom_xml_data_binding_sync_result;
struct date_field_options;
struct document_error_info;
struct document_property_field_options;
struct document_semantic_diff_category_summary;
struct document_semantic_diff_change;
struct document_semantic_diff_field_change;
struct document_semantic_diff_options;
struct document_semantic_diff_part_result;
struct document_semantic_diff_result;
struct drawing_image_info;
struct field_state_options;
struct field_summary;
struct floating_image_crop;
struct floating_image_options;
struct hyperlink_field_options;
struct hyperlink_summary;
struct imported_numbering_definition_summary;
struct index_entry_field_options;
struct index_field_options;
struct inline_image_info;
struct numbering_catalog;
struct numbering_catalog_definition;
struct numbering_catalog_import_summary;
struct numbering_definition;
struct numbering_definition_summary;
struct numbering_instance_lookup_summary;
struct numbering_instance_summary;
struct numbering_level_definition;
struct numbering_level_override_summary;
struct omml_summary;
struct page_margins;
struct page_reference_field_options;
struct paragraph_inspection_summary;
struct paragraph_style_definition;
struct paragraph_style_numbering_link;
struct reference_field_options;
struct resolved_style_bool_property;
struct resolved_style_double_property;
struct resolved_style_properties_summary;
struct resolved_style_string_property;
struct review_note_summary;
struct revision_metadata_update;
struct revision_summary;
struct revision_text_range_options;
struct run_inspection_summary;
struct section_inspection_summary;
struct section_page_setup;
struct section_part_inspection_summary;
struct sections_inspection_summary;
struct sequence_field_options;
struct style_prune_plan;
struct style_prune_summary;
struct style_refactor_apply_result;
struct style_refactor_issue;
struct style_refactor_operation_plan;
struct style_refactor_plan;
struct style_refactor_request;
struct style_refactor_restore_issue;
struct style_refactor_restore_issue_summary;
struct style_refactor_restore_operation_result;
struct style_refactor_restore_result;
struct style_refactor_rollback_entry;
struct style_refactor_suggestion;
struct style_refactor_suggestion_confidence_summary;
struct style_summary;
struct style_reference_field_options;
struct style_usage_breakdown;
struct style_usage_hit;
struct style_usage_hit_reference;
struct style_usage_report;
struct style_usage_report_entry;
struct style_usage_summary;
struct table_borders_inspection_summary;
struct table_cell_inspection_summary;
struct table_inspection_summary;
struct table_of_contents_field_options;
struct table_position;
struct table_style_border_summary;
struct table_style_borders_definition;
struct table_style_borders_summary;
struct table_style_definition;
struct table_style_definition_summary;
struct table_style_inheritance_audit_issue;
struct table_style_inheritance_audit_report;
struct table_style_look_consistency_issue;
struct table_style_look_consistency_report;
struct table_style_look_repair_report;
struct table_style_margins_definition;
struct table_style_paragraph_spacing_definition;
struct table_style_quality_audit_report;
struct table_style_quality_fix_item;
struct table_style_quality_fix_plan;
struct table_style_region_audit_issue;
struct table_style_region_audit_report;
struct table_style_region_definition;
struct table_style_region_summary;
struct template_kind_mismatch;
struct template_occurrence_mismatch;
struct template_onboarding_issue;
struct template_onboarding_next_action;
struct template_onboarding_options;
struct template_onboarding_result;
struct template_schema;
struct template_schema_entry;
struct template_schema_normalization_summary;
struct template_schema_part_selector;
struct template_schema_part_validation_result;
struct template_schema_patch;
struct template_schema_patch_review_summary;
struct template_schema_patch_summary;
struct template_schema_scan_options;
struct template_schema_scan_result;
struct template_schema_scan_skipped_bookmark;
struct template_schema_slot_patch_update;
struct template_schema_slot_rename;
struct template_schema_slot_selector;
struct template_schema_slot_update;
struct template_schema_validation_result;
struct template_slot_requirement;
struct template_validation_result;
struct template_table_selector;
struct text_range_preview;
struct text_range_preview_segment;

enum class body_block_kind : std::uint8_t;
enum class bookmark_kind : std::uint8_t;
enum class complex_field_instruction_fragment_kind : std::uint8_t;
enum class content_control_form_kind : std::uint8_t;
enum class content_control_kind : std::uint8_t;
enum class document_semantic_diff_change_kind : std::uint8_t;
enum class drawing_image_placement;
enum class field_kind : std::uint8_t;
enum class floating_image_horizontal_reference : std::uint8_t;
enum class floating_image_vertical_reference : std::uint8_t;
enum class floating_image_wrap_mode : std::uint8_t;
enum class page_orientation : std::uint8_t;
enum class review_note_kind : std::uint8_t;
enum class revision_kind : std::uint8_t;
enum class style_kind : std::uint8_t;
enum class style_refactor_action;
enum class style_usage_hit_kind;
enum class style_usage_part_kind;
enum class template_onboarding_issue_severity : std::uint8_t;
enum class template_onboarding_next_action_kind : std::uint8_t;
enum class template_schema_part_kind : std::uint8_t;
enum class template_schema_scan_target_mode : std::uint8_t;
enum class template_slot_kind : std::uint8_t;
enum class template_slot_source_kind : std::uint8_t;

} // namespace featherdoc
