            add_test(
                NAME
                check_numbering_catalog_baseline
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/check_numbering_catalog_baseline_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/check_numbering_catalog_baseline
            )

            add_test(
                NAME
                check_numbering_catalog_manifest
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/check_numbering_catalog_manifest_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/check_numbering_catalog_manifest
            )

            add_test(
                NAME
                check_template_schema_baseline
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/check_template_schema_baseline_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/check_template_schema_baseline
            )

            add_test(
                NAME
                check_template_schema_manifest
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/check_template_schema_manifest_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/check_template_schema_manifest
            )

            add_test(
                NAME
                run_project_template_smoke_schema_review
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/run_project_template_smoke_schema_review_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/run_project_template_smoke_schema_review
            )

            add_test(
                NAME
                sync_project_template_schema_approval
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/sync_project_template_schema_approval_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/sync_project_template_schema_approval
            )

            add_test(
                NAME
                write_project_template_schema_approval_history
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/write_project_template_schema_approval_history_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/write_project_template_schema_approval_history
            )

            add_test(
                NAME
                build_document_skeleton_governance_report_passing
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_report_passing
                -Scenario
                passing
            )

            add_test(
                NAME
                build_document_skeleton_governance_report_failing
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_report_failing
                -Scenario
                failing
            )

            add_test(
                NAME
                build_document_skeleton_governance_report_fail_on_issue
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_report_fail_on_issue
                -Scenario
                fail_on_issue
            )

            add_test(
                NAME
                build_document_skeleton_governance_rollup_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_rollup_report_aggregate
                -Scenario
                aggregate
            )

            add_test(
                NAME
                build_document_skeleton_governance_rollup_report_empty
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_rollup_report_empty
                -Scenario
                empty
            )

            add_test(
                NAME
                build_document_skeleton_governance_rollup_report_malformed
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_rollup_report_malformed
                -Scenario
                malformed
            )

            add_test(
                NAME
                build_document_skeleton_governance_rollup_report_failed_source_report
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_rollup_report_failed_source_report
                -Scenario
                failed_source_report
            )

            add_test(
                NAME
                build_document_skeleton_governance_rollup_report_fail_on_issue
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_document_skeleton_governance_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_document_skeleton_governance_rollup_report_fail_on_issue
                -Scenario
                fail_on_issue
            )

            add_test(
                NAME
                build_numbering_catalog_governance_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_numbering_catalog_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_numbering_catalog_governance_report_aggregate
                -Scenario
                aggregate
            )

            add_test(
                NAME
                build_numbering_catalog_governance_report_clean
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_numbering_catalog_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_numbering_catalog_governance_report_clean
                -Scenario
                clean
            )

            add_test(
                NAME
                build_numbering_catalog_governance_report_malformed
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_numbering_catalog_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_numbering_catalog_governance_report_malformed
                -Scenario
                malformed
            )

            add_test(
                NAME
                build_numbering_catalog_governance_report_fail_on_blocker
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_numbering_catalog_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_numbering_catalog_governance_report_fail_on_blocker
                -Scenario
                fail_on_blocker
            )

            add_test(
                NAME
                build_table_layout_delivery_report_passing
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_report_passing
                -Scenario
                passing
            )

            add_test(
                NAME
                build_table_layout_delivery_report_failing
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_report_failing
                -Scenario
                failing
            )

            add_test(
                NAME
                build_table_layout_delivery_report_fail_on_issue
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_report_fail_on_issue
                -Scenario
                fail_on_issue
            )

            add_test(
                NAME
                build_table_layout_delivery_rollup_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_rollup_report_aggregate
                -Scenario
                aggregate
            )

            add_test(
                NAME
                build_table_layout_delivery_rollup_report_empty
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_rollup_report_empty
                -Scenario
                empty
            )

            add_test(
                NAME
                build_table_layout_delivery_rollup_report_malformed
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_rollup_report_malformed
                -Scenario
                malformed
            )

            add_test(
                NAME
                build_table_layout_delivery_rollup_report_failed_source_report
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_rollup_report_failed_source_report
                -Scenario
                failed_source_report
            )

            add_test(
                NAME
                build_table_layout_delivery_rollup_report_fail_on_issue
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_rollup_report_fail_on_issue
                -Scenario
                fail_on_issue
            )

            add_test(
                NAME
                build_table_layout_delivery_rollup_report_fail_on_blocker
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_rollup_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_rollup_report_fail_on_blocker
                -Scenario
                fail_on_blocker
            )

            add_test(
                NAME
                build_table_layout_delivery_governance_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_governance_report_aggregate
                -Scenario
                aggregate
            )

            add_test(
                NAME
                build_table_layout_delivery_governance_report_ready
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_governance_report_ready
                -Scenario
                ready
            )

            add_test(
                NAME
                build_table_layout_delivery_governance_report_malformed
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_governance_report_malformed
                -Scenario
                malformed
            )

            add_test(
                NAME
                build_table_layout_delivery_governance_report_fail_on_issue
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_governance_report_fail_on_issue
                -Scenario
                fail_on_issue
            )
            set_tests_properties(build_table_layout_delivery_governance_report_fail_on_issue
                PROPERTIES
                    TIMEOUT 60)

            add_test(
                NAME
                build_table_layout_delivery_governance_report_fail_on_blocker
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_table_layout_delivery_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_table_layout_delivery_governance_report_fail_on_blocker
                -Scenario
                fail_on_blocker
            )

            add_test(
                NAME
                build_content_control_data_binding_governance_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_content_control_data_binding_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_content_control_data_binding_governance_report_aggregate
                -Scenario
                aggregate
            )
            set_tests_properties(build_content_control_data_binding_governance_report_aggregate
                PROPERTIES
                    TIMEOUT 60
                    LABELS "docs;smoke;governance;content-control")

            add_test(
                NAME
                build_content_control_data_binding_governance_report_fail_on_blocker
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_content_control_data_binding_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_content_control_data_binding_governance_report_fail_on_blocker
                -Scenario
                fail_on_blocker
            )
            set_tests_properties(build_content_control_data_binding_governance_report_fail_on_blocker
                PROPERTIES
                    TIMEOUT 60
                    LABELS "docs;smoke;governance;content-control")

            add_test(
                NAME
                build_content_control_data_binding_governance_report_fail_on_warning
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_content_control_data_binding_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_content_control_data_binding_governance_report_fail_on_warning
                -Scenario
                fail_on_warning
            )
            set_tests_properties(build_content_control_data_binding_governance_report_fail_on_warning
                PROPERTIES
                    TIMEOUT 60
                    LABELS "docs;smoke;governance;content-control")

            add_test(
                NAME
                table_layout_delivery_report
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/table_layout_delivery_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -BuildDir
                ${PROJECT_BINARY_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/table_layout_delivery_report
            )

            add_test(
                NAME
                build_project_template_onboarding_governance_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_project_template_onboarding_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_project_template_onboarding_governance_report_aggregate
                -Scenario
                aggregate
            )

            add_test(
                NAME
                build_project_template_onboarding_governance_report_fail_on_blocker
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_project_template_onboarding_governance_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_project_template_onboarding_governance_report_fail_on_blocker
                -Scenario
                fail_on_blocker
            )

            add_test(
                NAME
                build_project_template_delivery_readiness_report_aggregate
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_project_template_delivery_readiness_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_project_template_delivery_readiness_report_aggregate
                -Scenario
                aggregate
            )

            add_test(
                NAME
                build_project_template_delivery_readiness_report_ready
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_project_template_delivery_readiness_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_project_template_delivery_readiness_report_ready
                -Scenario
                ready
            )

            add_test(
                NAME
                build_project_template_delivery_readiness_report_malformed
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_project_template_delivery_readiness_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_project_template_delivery_readiness_report_malformed
                -Scenario
                malformed
            )

            add_test(
                NAME
                build_project_template_delivery_readiness_report_fail_on_blocker
                COMMAND
                ${FEATHERDOC_POWERSHELL_TEST_COMMAND}
                -ExecutionPolicy
                Bypass
                -File
                ${CMAKE_CURRENT_SOURCE_DIR}/build_project_template_delivery_readiness_report_test.ps1
                -RepoRoot
                ${PROJECT_SOURCE_DIR}
                -WorkingDir
                ${CMAKE_CURRENT_BINARY_DIR}/build_project_template_delivery_readiness_report_fail_on_blocker
                -Scenario
                fail_on_blocker
            )
