#include "featherdoc_cli_usage.hpp"

#include <ostream>

namespace featherdoc_cli {

void print_usage(std::ostream &stream) {
    stream
        << "Usage:\n"
        << "  featherdoc_cli run-recipe --recipe <recipe.json>"
           " --inputs <inputs.json> --output <output-dir> [--json]\n"
        << "  featherdoc_cli export-pdf <input.docx> --output <output.pdf>"
           " [--render-headers-and-footers] [--render-inline-images]"
           " [--font-file <path>] [--cjk-font-file <path>]"
           " [--font-map <family>=<path>]..."
           " [--title <text>] [--creator <text>] [--no-font-subset]"
           " [--no-system-font-fallbacks]"
           " [--summary-json <path>] [--json]\n"
        << "  featherdoc_cli inspect-sections <input.docx>\n"
        << "    [--json]\n"
        << "  featherdoc_cli inspect-styles <input.docx>"
           " [--style <style-id>] [--usage] [--json]\n"
        << "  featherdoc_cli inspect-style-inheritance <input.docx> <style-id>"
           " [--json]\n"
        << "  featherdoc_cli rename-style <input.docx> <old-style-id>"
           " <new-style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-style <input.docx> <source-style-id>"
           " <target-style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli plan-style-refactor <input.docx>"
           " [--rename <old:new>] [--merge <source:target>]"
           " [--output-plan <path>] [--json]\n"
        << "  featherdoc_cli suggest-style-merges <input.docx>"
           " [--confidence-profile recommended|strict|review|exploratory]"
           " [--min-confidence <0-100>] [--source-style <id>]..."
           " [--target-style <id>]... [--fail-on-suggestion]"
           " [--output-plan <path>] [--json]\n"
        << "  featherdoc_cli apply-style-refactor <input.docx>"
           " [--plan-file <path> | --rename <old:new> | --merge <source:target>]"
           " [--rollback-plan <path>] [--output <path>] [--json]\n"
        << "  featherdoc_cli restore-style-merge <input.docx>"
           " --rollback-plan <path> [--entry <index>]..."
           " [--source-style <id>]... [--target-style <id>]..."
           " [--dry-run | --output <path>] [--json]\n"
        << "  featherdoc_cli plan-prune-unused-styles <input.docx>"
           " [--json]\n"
        << "  featherdoc_cli prune-unused-styles <input.docx>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-numbering <input.docx>"
           " [--definition <id>] [--instance <num-id>] [--json]\n"
        << "  featherdoc_cli inspect-style-numbering <input.docx> [--json]\n"
        << "  featherdoc_cli audit-style-numbering <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli audit-table-style-regions <input.docx>"
           " [--style <style-id>] [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli audit-table-style-inheritance <input.docx>"
           " [--style <style-id>] [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli audit-table-style-quality <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli plan-table-style-quality-fixes <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli apply-table-style-quality-fixes <input.docx>"
           " --look-only --output <path> [--json]\n"
        << "  featherdoc_cli repair-style-numbering <input.docx>"
           " [--catalog-file <catalog.json>] [--plan-only | --apply --output <path>] [--json]\n"
        << "  featherdoc_cli export-numbering-catalog <input.docx>"
           " [--output <catalog.json>] [--json]\n"
        << "  featherdoc_cli check-numbering-catalog <input.docx>"
           " --catalog-file <catalog.json>"
           " [--output <generated-catalog.json>] [--json]\n"
        << "  featherdoc_cli import-numbering-catalog <input.docx>"
           " --catalog-file <catalog.json> [--output <path>] [--json]\n"
        << "  featherdoc_cli patch-numbering-catalog <catalog.json>"
           " --patch-file <patch.json> [--output <catalog.json>] [--json]\n"
        << "  featherdoc_cli lint-numbering-catalog <catalog.json> [--json]\n"
        << "  featherdoc_cli diff-numbering-catalog <left-catalog.json>"
           " <right-catalog.json> [--fail-on-diff] [--json]\n"
        << "  featherdoc_cli inspect-paragraphs <input.docx>"
           " [--paragraph <index>] [--json]\n"
        << "  featherdoc_cli inspect-tables <input.docx>"
           " [--table <index>] [--json]\n"
        << "  featherdoc_cli semantic-diff <left.docx> <right.docx>"
           " [--fail-on-diff] [--index-alignment]"
           " [--alignment-cell-limit <count>]"
           " [--include-image-relationship-ids]"
           " [--include-content-control-ids] [--no-fields]"
           " [--no-styles] [--no-numbering]"
           " [--no-footnotes] [--no-endnotes] [--no-comments] [--no-revisions]"
           " [--no-template-parts] [--no-resolved-section-template-parts]"
           " [--no-sections] [--json]\n"
        << "  featherdoc_cli plan-table-position-presets <input.docx>"
           " --preset paragraph-callout|page-corner|margin-anchor"
           " [--replace-positioned] [--fail-on-change]"
           " [--output <path>] [--output-plan <plan.json>] [--json]\n"
        << "  featherdoc_cli apply-table-position-plan <plan.json>"
           " [--output <path>] [--dry-run] [--json]\n"
        << "  featherdoc_cli set-table-position <input.docx> <table-index|all>"
           " [--table <index>]..."
           " (--preset paragraph-callout|page-corner|margin-anchor |"
           " --horizontal-reference margin|page|column --horizontal-offset <twips>"
           " --vertical-reference margin|page|paragraph --vertical-offset <twips>)"
           " [--left-from-text <twips>] [--right-from-text <twips>]"
           " [--top-from-text <twips>] [--bottom-from-text <twips>]"
           " [--overlap allow|never] [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-position <input.docx> <table-index|all>"
           " [--table <index>]... [--output <path>] [--json]\n"
        << "  featherdoc_cli check-table-style-look <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli repair-table-style-look <input.docx>"
           " [--plan-only | --apply --output <path>] [--json]\n"
        << "  featherdoc_cli inspect-table-cells <input.docx> <table-index>"
           " [--row <index>] [--cell <index>|--grid-column <index>] [--json]\n"
        << "  featherdoc_cli inspect-table-rows <input.docx> <table-index>"
           " [--row <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-paragraphs <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--paragraph <index>] [--json]\n"
        << "  featherdoc_cli append-table-row <input.docx> <table-index>"
           " [--cell-count <n>] [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-row-before <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-row-after <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-table-row <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-text <input.docx> <table-index>"
           " <row-index> (<cell-index>|--grid-column <index>)"
           " (--text <text> | --text-file <path>)"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-table-cells <input.docx> <table-index>"
           " <row-index> <cell-index> --direction <right|down>"
           " [--count <n>] [--output <path>] [--json]\n"
        << "  featherdoc_cli unmerge-table-cells <input.docx> <table-index>"
           " <row-index> <cell-index> --direction <right|down>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-fill <input.docx> <table-index>"
           " <row-index> <cell-index> <hex-color> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-fill <input.docx> <table-index>"
           " <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-vertical-alignment <input.docx>"
           " <table-index> <row-index> <cell-index> <top|center|bottom|both>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-vertical-alignment <input.docx>"
           " <table-index> <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-text-direction <input.docx>"
           " <table-index> <row-index> <cell-index>"
           " <left_to_right_top_to_bottom|top_to_bottom_right_to_left|bottom_to_top_left_to_right|left_to_right_top_to_bottom_rotated|top_to_bottom_right_to_left_rotated|top_to_bottom_left_to_right_rotated>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-text-direction <input.docx>"
           " <table-index> <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-width <input.docx> <table-index>"
           " <row-index> <cell-index> <width-twips>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-width <input.docx> <table-index>"
           " <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-margin <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right> <margin-twips>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-margin <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-border <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right>"
           " --style <none|single|double_line|dashed|dotted|thick>"
           " [--size <n>] [--color <value>] [--space <n>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-border <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-row-height <input.docx> <table-index>"
           " <row-index> <height-twips> <automatic|at_least|exact>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-row-height <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-row-cant-split <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-row-cant-split <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-row-repeat-header <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-row-repeat-header <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-runs <input.docx> <paragraph-index>"
           " [--run <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-runs <input.docx> <paragraph-index>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--run <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-tables <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--table <index>|--bookmark <name>] [--json]\n"
        << "  featherdoc_cli inspect-template-table-rows <input.docx>"
           " [<table-index>|--bookmark <name>|--after-text <text>|"
           " --header-cell <text> ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--row <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-table-cells <input.docx>"
           " [<table-index>|--bookmark <name>|--after-text <text>|"
           " --header-cell <text> ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--row <index>] [--cell <index>|--grid-column <index>] [--json]\n"
        << "  featherdoc_cli set-template-table-cell-text <input.docx>"
           " (<table-index> <row-index> (<cell-index>|--grid-column <index>)|"
           " --bookmark <name> <row-index> (<cell-index>|--grid-column <index>)|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> (<cell-index>|--grid-column <index>))"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " (--text <text> | --text-file <path>)"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-table-row-texts <input.docx>"
           " (<table-index> <start-row-index>|"
           " --bookmark <name> <start-row-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <start-row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " (--row <text> [--cell <text> ...])+"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-table-cell-block-texts <input.docx>"
           " (<table-index> <start-row-index> <start-cell-index>|"
           " --bookmark <name> <start-row-index> <start-cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <start-row-index> <start-cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " (--row <text> [--cell <text> ...])+"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-table-from-json <input.docx>"
           " [<table-index>|--bookmark <name>|--after-text <text>|"
           " --header-cell <text> ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " --patch-file <path> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-tables-from-json <input.docx>"
           " --patch-file <path>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-column-before <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-column-after <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-template-table-column <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-template-table-row <input.docx>"
           " (<table-index>|--bookmark <name>|"
           " --after-text <text>|--header-cell <text> ...)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--cell-count <n>] [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-row-before <input.docx>"
           " (<table-index> <row-index>|--bookmark <name> <row-index>|"
           " [--after-text <text>|--header-cell <text> ...] <row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-row-after <input.docx>"
           " (<table-index> <row-index>|--bookmark <name> <row-index>|"
           " [--after-text <text>|--header-cell <text> ...] <row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-template-table-row <input.docx>"
           " (<table-index> <row-index>|--bookmark <name> <row-index>|"
           " [--after-text <text>|--header-cell <text> ...] <row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-template-table-cells <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " --direction <right|down> [--count <n>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli unmerge-template-table-cells <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " --direction <right|down> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-paragraph-style <input.docx> <paragraph-index>"
           " <style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-paragraph-style <input.docx> <paragraph-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-run-style <input.docx> <paragraph-index>"
           " <run-index> <style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-run-style <input.docx> <paragraph-index>"
           " <run-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-run-font-family <input.docx> <paragraph-index>"
           " <run-index> <font-family> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-run-font-family <input.docx> <paragraph-index>"
           " <run-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-run-language <input.docx> <paragraph-index>"
           " <run-index> <language> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-run-language <input.docx> <paragraph-index>"
           " <run-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-default-run-properties <input.docx>"
           " [--json]\n"
        << "  featherdoc_cli set-default-run-properties <input.docx>"
           " [--font-family <name>] [--east-asia-font-family <name>]"
           " [--language <tag>] [--east-asia-language <tag>]"
           " [--bidi-language <tag>] [--rtl true|false]"
           " [--paragraph-bidi true|false] [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-default-run-properties <input.docx>"
           " [--font-family] [--east-asia-font-family] [--primary-language]"
           " [--language] [--east-asia-language] [--bidi-language] [--rtl]"
           " [--paragraph-bidi] [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-style-run-properties <input.docx> <style-id>"
           " [--json]\n"
        << "  featherdoc_cli inspect-paragraph-style-properties <input.docx> <style-id>"
           " [--json]\n"
        << "  featherdoc_cli inspect-table-style <input.docx> <style-id>"
           " [--json]\n"
        << "  featherdoc_cli materialize-style-run-properties <input.docx> <style-id>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli rebase-character-style-based-on <input.docx> <style-id>"
           " <based-on-style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli rebase-paragraph-style-based-on <input.docx> <style-id>"
           " <based-on-style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-paragraph-style-properties <input.docx> <style-id>"
           " [--based-on <style-id>] [--next-style <style-id>]"
           " [--outline-level <0-8>] [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-paragraph-style-properties <input.docx> <style-id>"
           " [--based-on] [--next-style] [--outline-level]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-style-run-properties <input.docx> <style-id>"
           " [--font-family <name>] [--east-asia-font-family <name>]"
           " [--language <tag>] [--east-asia-language <tag>]"
           " [--bidi-language <tag>] [--rtl true|false]"
           " [--paragraph-bidi true|false] [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-style-run-properties <input.docx> <style-id>"
           " [--font-family] [--east-asia-font-family] [--primary-language]"
           " [--language] [--east-asia-language] [--bidi-language] [--rtl]"
           " [--paragraph-bidi] [--output <path>] [--json]\n"
        << "  featherdoc_cli ensure-paragraph-style <input.docx> <style-id>"
           " --name <name> [--based-on <style-id>] [--next-style <style-id>]"
           " [--custom true|false] [--semi-hidden true|false]"
           " [--unhide-when-used true|false] [--quick-format true|false]"
           " [--run-font-family <name>] [--run-east-asia-font-family <name>]"
           " [--run-language <tag>] [--run-east-asia-language <tag>]"
           " [--run-bidi-language <tag>] [--run-rtl true|false]"
           " [--paragraph-bidi true|false] [--outline-level <0-8>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli ensure-character-style <input.docx> <style-id>"
           " --name <name> [--based-on <style-id>] [--custom true|false]"
           " [--semi-hidden true|false] [--unhide-when-used true|false]"
           " [--quick-format true|false] [--run-font-family <name>]"
           " [--run-east-asia-font-family <name>] [--run-language <tag>]"
           " [--run-east-asia-language <tag>] [--run-bidi-language <tag>]"
           " [--run-rtl true|false] [--output <path>] [--json]\n"
        << "  featherdoc_cli ensure-table-style <input.docx> <style-id>"
           " --name <name> [--based-on <style-id>] [--custom true|false]"
           " [--semi-hidden true|false] [--unhide-when-used true|false]"
           " [--quick-format true|false] [--style-fill <region>:<color>]"
           " [--style-text-color <region>:<color>]"
           " [--style-bold <region>:true|false]"
           " [--style-italic <region>:true|false]"
           " [--style-font-size <region>:<points>]"
           " [--style-font-family <region>:<name>]"
           " [--style-east-asia-font-family <region>:<name>]"
           " [--style-cell-vertical-alignment <region>:<top|center|bottom|both>]"
           " [--style-cell-text-direction <region>:<direction>]"
           " [--style-paragraph-alignment <region>:<left|center|right|justified|distribute>]"
           " [--style-paragraph-spacing-before <region>:<twips>]"
           " [--style-paragraph-spacing-after <region>:<twips>]"
           " [--style-paragraph-line-spacing <region>:<twips>:<auto|at_least|exact>]"
           " [--style-margin <region>:<edge>:<twips>]"
           " [--style-border <region>:<edge>:<style>:<size>:<color>[:space]]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli ensure-style-linked-numbering <input.docx>"
           " --definition-name <name>"
           " --numbering-level <level>:<kind>:<start>:<text-pattern>"
           " [--numbering-level ...] --style-link <style-id>:<level>"
           " [--style-link ...] [--output <path>] [--json]\n"
        << "  featherdoc_cli set-paragraph-style-numbering <input.docx> <style-id>"
           " --definition-name <name>"
           " --numbering-level <level>:<kind>:<start>:<text-pattern>"
           " [--numbering-level ...] [--style-level <level>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-paragraph-style-numbering <input.docx> <style-id>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli ensure-numbering-definition <input.docx>"
           " --definition-name <name>"
           " --numbering-level <level>:<kind>:<start>:<text-pattern>"
           " [--numbering-level ...] [--output <path>] [--json]\n"
        << "  featherdoc_cli set-paragraph-numbering <input.docx> <paragraph-index>"
           " --definition <id> [--level <level>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-paragraph-list <input.docx> <paragraph-index>"
           " --kind bullet|decimal [--level <level>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli restart-paragraph-list <input.docx> <paragraph-index>"
           " --kind bullet|decimal [--level <level>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-paragraph-list <input.docx> <paragraph-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-page-setup <input.docx>"
           " [--section <section-index>] [--json]\n"
        << "  featherdoc_cli set-section-page-setup <input.docx> <section-index>"
           " [--orientation portrait|landscape] [--width <twips>]"
           " [--height <twips>] [--margin-top <twips>]"
           " [--margin-bottom <twips>] [--margin-left <twips>]"
           " [--margin-right <twips>] [--margin-header <twips>]"
           " [--margin-footer <twips>] [--page-number-start <n> |"
           " --clear-page-number-start] [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-update-fields-on-open <input.docx> [--json]\n"
        << "  featherdoc_cli set-update-fields-on-open <input.docx>"
           " --enable|--disable [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-bookmarks <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--bookmark <name>] [--json]\n"
        << "  featherdoc_cli inspect-content-controls <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--tag <tag>] [--alias <alias>]"
           " [--json]\n"
        << "  featherdoc_cli inspect-hyperlinks <input.docx> [--json]\n"
        << "  featherdoc_cli inspect-review <input.docx> [--json]\n"
        << "  featherdoc_cli preview-text-range <input.docx>"
           " <start-paragraph-index> <start-offset>"
           " <end-paragraph-index> <end-offset> [--json]\n"
        << "  featherdoc_cli find-text-ranges <input.docx>"
           " --text <text> [--json]\n"
        << "  featherdoc_cli build-review-mutation-plan <input.docx>"
           " --request-file <request.json> [--output-plan <plan.json>]"
           " [--json]\n"
        << "  featherdoc_cli preview-review-mutation-plan <input.docx>"
           " --plan-file <plan.json> [--json]\n"
        << "  featherdoc_cli apply-review-mutation-plan <input.docx>"
           " --plan-file <plan.json> [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-omml <input.docx> [--json]\n"
        << "  featherdoc_cli append-hyperlink <input.docx>"
           " --text <text> --target <url> [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-hyperlink <input.docx> <hyperlink-index>"
           " --text <text> --target <url> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-hyperlink <input.docx> <hyperlink-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-omml <input.docx> --xml <omml-xml>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-omml <input.docx> <formula-index>"
           " --xml <omml-xml> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-omml <input.docx> <formula-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-insertion-revision <input.docx>"
           " --text <text> [--author <name>] [--date <iso>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-deletion-revision <input.docx>"
           " --text <text> [--author <name>] [--date <iso>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-run-revision-after <input.docx>"
           " <paragraph-index> <run-index> --text <text>"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli delete-run-revision <input.docx>"
           " <paragraph-index> <run-index>"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-run-revision <input.docx>"
           " <paragraph-index> <run-index> --text <text>"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-paragraph-text-revision <input.docx>"
           " <paragraph-index> <offset> --text <text>"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli delete-paragraph-text-revision <input.docx>"
           " <paragraph-index> <offset> <length>"
           " [--expected-text <text>]"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-paragraph-text-revision <input.docx>"
           " <paragraph-index> <offset> <length> --text <text>"
           " [--expected-text <text>]"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-text-range-revision <input.docx>"
           " <paragraph-index> <offset> --text <text>"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli delete-text-range-revision <input.docx>"
           " <start-paragraph-index> <start-offset>"
           " <end-paragraph-index> <end-offset>"
           " [--expected-text <text>]"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-text-range-revision <input.docx>"
           " <start-paragraph-index> <start-offset>"
           " <end-paragraph-index> <end-offset> --text <text>"
           " [--expected-text <text>]"
           " [--author <name>] [--date <iso>] [--output <path>] [--json]\n"
        << "  featherdoc_cli accept-revision <input.docx> <revision-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli reject-revision <input.docx> <revision-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli accept-all-revisions <input.docx>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli reject-all-revisions <input.docx>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-revision-metadata <input.docx>"
           " <revision-index>"
           " [--author <name>|--clear-author]"
           " [--date <iso>|--clear-date]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-footnote <input.docx>"
           " --reference-text <text> --note-text <text>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-footnote <input.docx> <note-index>"
           " --note-text <text> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-footnote <input.docx> <note-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-endnote <input.docx>"
           " --reference-text <text> --note-text <text>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-endnote <input.docx> <note-index>"
           " --note-text <text> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-endnote <input.docx> <note-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-comment <input.docx>"
           " --selected-text <text> --comment-text <text>"
           " [--author <name>] [--initials <text>] [--date <iso>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-paragraph-text-comment <input.docx>"
           " <paragraph-index> <offset> <length> --comment-text <text>"
           " [--author <name>] [--initials <text>] [--date <iso>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-text-range-comment <input.docx>"
           " <start-paragraph-index> <start-offset>"
           " <end-paragraph-index> <end-offset> --comment-text <text>"
           " [--author <name>] [--initials <text>] [--date <iso>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-comment-reply <input.docx>"
           " <parent-comment-index> --comment-text <text>"
           " [--author <name>] [--initials <text>] [--date <iso>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-paragraph-text-comment-range <input.docx>"
           " <comment-index> <paragraph-index> <offset> <length>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-text-range-comment-range <input.docx>"
           " <comment-index> <start-paragraph-index> <start-offset>"
           " <end-paragraph-index> <end-offset>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-comment-resolved <input.docx>"
           " <comment-index> <true|false> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-comment-metadata <input.docx>"
           " <comment-index>"
           " [--author <name>|--clear-author]"
           " [--initials <text>|--clear-initials]"
           " [--date <iso>|--clear-date]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-comment <input.docx> <comment-index>"
           " --comment-text <text> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-comment <input.docx> <comment-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-content-control-text <input.docx>"
           " (--tag <tag> | --alias <alias>) --text <text>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli set-content-control-form-state <input.docx>"
           " (--tag <tag> | --alias <alias>)"
           " [--lock <val> | --clear-lock] [--checked <true|false>]"
           " [--selected-item <display-or-value>] [--date-text <text>]"
           " [--date-format <fmt>] [--date-locale <locale>]"
           " [--data-binding-store-item-id <id>] [--data-binding-xpath <xpath>]"
           " [--data-binding-prefix-mappings <mappings> | --clear-data-binding]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli sync-content-controls-from-custom-xml <input.docx>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-content-control-paragraphs <input.docx>"
           " (--tag <tag> | --alias <alias>)"
           " (--paragraph <text> | --paragraph-file <path>)"
           " [(--paragraph <text> | --paragraph-file <path>) ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-content-control-table <input.docx>"
           " (--tag <tag> | --alias <alias>)"
           " ((--row <text> | --row-file <path>)"
           " [(--cell <text> | --cell-file <path>) ...])+"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-content-control-table-rows <input.docx>"
           " (--tag <tag> | --alias <alias>)"
           " (((--row <text> | --row-file <path>)"
           " [(--cell <text> | --cell-file <path>) ...])+ | --empty)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-content-control-image <input.docx>"
           " <image-path> (--tag <tag> | --alias <alias>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--width <px>] [--height <px>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-bookmark-text <input.docx>"
           " <bookmark-name> --text <text>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli fill-bookmarks <input.docx>"
           " ((--set <bookmark-name> <text>) |"
           " (--set-file <bookmark-name> <path>))+"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-bookmark-paragraphs <input.docx>"
           " <bookmark-name>"
           " (--paragraph <text> | --paragraph-file <path>)"
           " [(--paragraph <text> | --paragraph-file <path>) ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-bookmark-table <input.docx>"
           " <bookmark-name>"
           " ((--row <text> | --row-file <path>)"
           " [(--cell <text> | --cell-file <path>) ...])+"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-bookmark-table-rows <input.docx>"
           " <bookmark-name>"
           " (((--row <text> | --row-file <path>)"
           " [(--cell <text> | --cell-file <path>) ...])+ | --empty)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-bookmark-block <input.docx> <bookmark-name>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli set-bookmark-block-visibility <input.docx>"
           " <bookmark-name> --visible true|false"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli apply-bookmark-block-visibility <input.docx>"
           " (--show <bookmark-name> | --hide <bookmark-name>)+"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-bookmark-image <input.docx> <bookmark-name>"
           " <image-path> [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--width <px>] [--height <px>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli replace-bookmark-floating-image <input.docx>"
           " <bookmark-name> <image-path>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--width <px>] [--height <px>]"
           " [--horizontal-reference page|margin|column|character]"
           " [--horizontal-offset <px>]"
           " [--vertical-reference page|margin|paragraph|line]"
           " [--vertical-offset <px>] [--behind-text true|false]"
           " [--allow-overlap true|false] [--z-order <value>]"
           " [--wrap-mode none|square|top-bottom]"
           " [--wrap-distance-left <px>] [--wrap-distance-right <px>]"
           " [--wrap-distance-top <px>] [--wrap-distance-bottom <px>]"
           " [--crop-left <per-mille>] [--crop-top <per-mille>]"
           " [--crop-right <per-mille>] [--crop-bottom <per-mille>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-images <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--relationship-id <id>]"
           " [--image-entry-name <path>] [--image <index>] [--json]\n"
        << "  featherdoc_cli extract-image <input.docx> <output-path>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--relationship-id <id>]"
           " [--image-entry-name <path>] [--image <index>] [--json]\n"
        << "  featherdoc_cli replace-image <input.docx> <image-path>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--relationship-id <id>]"
           " [--image-entry-name <path>] [--image <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-image <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--relationship-id <id>]"
           " [--image-entry-name <path>] [--image <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-image <input.docx> <image-path>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--width <px>] [--height <px>]"
           " [--floating] [--horizontal-reference page|margin|column|character]"
           " [--horizontal-offset <px>]"
           " [--vertical-reference page|margin|paragraph|line]"
           " [--vertical-offset <px>] [--behind-text true|false]"
           " [--allow-overlap true|false] [--z-order <value>]"
           " [--wrap-mode none|square|top-bottom]"
           " [--wrap-distance-left <px>] [--wrap-distance-right <px>]"
           " [--wrap-distance-top <px>] [--wrap-distance-bottom <px>]"
           " [--crop-left <per-mille>] [--crop-top <per-mille>]"
           " [--crop-right <per-mille>] [--crop-bottom <per-mille>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-section <input.docx> <section-index>"
           " [--no-inherit] [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-section <input.docx> <section-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli move-section <input.docx> <source-index>"
           " <target-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli copy-section-layout <input.docx> <source-index>"
           " <target-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-header-parts <input.docx> [--json]\n"
        << "  featherdoc_cli inspect-footer-parts <input.docx> [--json]\n"
        << "  featherdoc_cli assign-section-header <input.docx> <section-index>"
           " <header-index> [--kind default|first|even] [--output <path>]"
           " [--json]\n"
        << "  featherdoc_cli assign-section-footer <input.docx> <section-index>"
           " <footer-index> [--kind default|first|even] [--output <path>]"
           " [--json]\n"
        << "  featherdoc_cli remove-section-header <input.docx> <section-index>"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-section-footer <input.docx> <section-index>"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-header-part <input.docx> <header-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-footer-part <input.docx> <footer-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli move-header-part <input.docx> <source-index>"
           " <target-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli move-footer-part <input.docx> <source-index>"
           " <target-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli show-section-header <input.docx> <section-index>"
           " [--kind default|first|even] [--json]\n"
        << "  featherdoc_cli show-section-footer <input.docx> <section-index>"
           " [--kind default|first|even] [--json]\n"
        << "  featherdoc_cli set-section-header <input.docx> <section-index>"
           " (--text <text> | --text-file <path>)"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli set-section-footer <input.docx> <section-index>"
           " (--text <text> | --text-file <path>)"
           " [--kind default|first|even] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-page-number-field <input.docx>"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--dirty] [--locked]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-total-pages-field <input.docx>"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--dirty] [--locked]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-page-reference-field <input.docx>"
           " <bookmark-name> --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--result-text <text>]"
           " [--no-hyperlink] [--relative-position] [--dirty] [--locked]"
           " [--no-preserve-formatting] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-style-reference-field <input.docx>"
           " <style-name> --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--result-text <text>]"
           " [--paragraph-number] [--relative-position] [--dirty] [--locked]"
           " [--no-preserve-formatting] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-document-property-field <input.docx>"
           " <property-name> --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--result-text <text>]"
           " [--dirty] [--locked] [--no-preserve-formatting] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-date-field <input.docx>"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--format <word-date-format>]"
           " [--result-text <text>] [--dirty] [--locked]"
           " [--no-preserve-formatting] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-hyperlink-field <input.docx>"
           " <target> --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--anchor <bookmark>]"
           " [--tooltip <text>] [--result-text <text>] [--dirty] [--locked]"
           " [--no-preserve-formatting] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-caption <input.docx> <label>"
           " --text <caption-text> --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--number-result <text>]"
           " [--number-format <format>] [--restart <n>] [--separator <text>]"
           " [--dirty] [--locked] [--no-preserve-formatting]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-index-entry-field <input.docx> <entry-text>"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--subentry <text>]"
           " [--bookmark <name>] [--cross-reference <text>]"
           " [--bold-page-number] [--italic-page-number]"
           " [--dirty] [--locked] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-index-field <input.docx>"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--columns <n>]"
           " [--result-text <text>] [--dirty] [--locked]"
           " [--no-preserve-formatting] [--output <path>] [--json]\n"
        << "  featherdoc_cli append-complex-field <input.docx>"
           " (--instruction <text> | --instruction-before <text>"
           " --nested-instruction <text> [--nested-result-text <text>]"
           " --instruction-after <text>)"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--result-text <text>]"
           " [--dirty] [--locked] [--output <path>] [--json]\n"
        << "  featherdoc_cli validate-template <input.docx>"
           " --part body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " --slot <bookmark>:<kind>[:required|optional][:count=<n>|min=<n>|max=<n>...]"
           " [--slot ...] [--json]\n"
        << "  featherdoc_cli validate-template-schema <input.docx>"
           " [--schema-file <path>]"
           " (--target body|header|footer|section-header|section-footer"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " --slot <bookmark>:<kind>[:required|optional][:count=<n>|min=<n>|max=<n>...]"
           " [--slot ...])+ [--json]\n"
        << "  featherdoc_cli export-template-schema <input.docx>"
           " [--section-targets|--resolved-section-targets]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli normalize-template-schema <schema.json>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli lint-template-schema <schema.json> [--json]\n"
        << "  featherdoc_cli repair-template-schema <schema.json>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-template-schema <schema-a.json>"
           " <schema-b.json> [<schema-c.json> ...]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli patch-template-schema <schema.json>"
           " --patch-file <patch.json> [--output <path>] [--json]\n"
        << "  featherdoc_cli preview-template-schema-patch <schema.json>"
           " (--patch-file <patch.json>|<right-schema.json>)"
           " [--output-patch <path>] [--review-json <path>] [--json]\n"
        << "  featherdoc_cli build-template-schema-patch <left-schema.json>"
           " <right-schema.json> [--output <path>] [--review-json <path>] [--json]\n"
        << "  featherdoc_cli diff-template-schema <left-schema.json>"
           " <right-schema.json> [--fail-on-diff] [--json]\n"
        << "  featherdoc_cli check-template-schema <input.docx>"
           " --schema-file <path>"
           " [--section-targets|--resolved-section-targets]"
           " [--output <generated-schema-path>] [--json]\n";
}

} // namespace featherdoc_cli
