#include "featherdoc_cli_usage_table.hpp"

#include <ostream>

namespace featherdoc_cli {

void print_table_usage(std::ostream &stream) {
    stream
        << "  featherdoc_cli plan-table-position-presets <input.docx>"
           " --preset paragraph-callout|page-corner|margin-anchor"
           " [--replace-positioned] [--fail-on-change]"
           " [--output <path>] [--output-plan <plan.json>] [--json]\n"
        << "  featherdoc_cli apply-table-position-plan <plan.json>"
           " [--output <path>] [--dry-run] [--json]\n"
        << "  featherdoc_cli set-table-position <input.docx> <table-index|all>"
           " [--table <index>]..."
           " (--preset paragraph-callout|page-corner|margin-anchor |"
           " --horizontal-reference margin|page|column --horizontal-offset <twips>"
           " --vertical-reference margin|page|paragraph --vertical-offset <twips>)"
           " [--horizontal-spec left|center|right|inside|outside]"
           " [--vertical-spec top|center|bottom|inside|outside]"
           " [--left-from-text <twips>] [--right-from-text <twips>]"
           " [--top-from-text <twips>] [--bottom-from-text <twips>]"
           " [--overlap allow|never] [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-position <input.docx> <table-index|all>"
           " [--table <index>]... [--output <path>] [--json]\n"
        << "  featherdoc_cli check-table-style-look <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli repair-table-style-look <input.docx>"
           " [--plan-only | --apply --output <path>] [--json]\n"
        << "  featherdoc_cli inspect-table-cells <input.docx> <table-index>"
           " [--row <index>] [--cell <index>|--grid-column <index>] [--json]\n"
        << "  featherdoc_cli inspect-table-rows <input.docx> <table-index>"
           " [--row <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-paragraphs <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--paragraph <index>] [--json]\n"
        << "  featherdoc_cli append-table-row <input.docx> <table-index>"
           " [--cell-count <n>] [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-row-before <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-row-after <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-table-row <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-before <input.docx> <table-index>"
           " <row-count> <column-count> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-after <input.docx> <table-index>"
           " <row-count> <column-count> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-like-before <input.docx>"
           " <table-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-like-after <input.docx>"
           " <table-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-paragraph-after-table <input.docx>"
           " <table-index> (--text <text> | --text-file <path>)"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-table <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-column-before <input.docx>"
           " <table-index> <row-index> <cell-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-table-column-after <input.docx>"
           " <table-index> <row-index> <cell-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-table-column <input.docx> <table-index>"
           " <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-text <input.docx> <table-index>"
           " <row-index> (<cell-index>|--grid-column <index>)"
           " (--text <text> | --text-file <path>)"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-table-cells <input.docx> <table-index>"
           " <row-index> <cell-index> --direction <right|down>"
           " [--count <n>] [--output <path>] [--json]\n"
        << "  featherdoc_cli unmerge-table-cells <input.docx> <table-index>"
           " <row-index> <cell-index> --direction <right|down>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-fill <input.docx> <table-index>"
           " <row-index> <cell-index> <hex-color> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-fill <input.docx> <table-index>"
           " <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-vertical-alignment <input.docx>"
           " <table-index> <row-index> <cell-index> <top|center|bottom|both>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-vertical-alignment <input.docx>"
           " <table-index> <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-text-direction <input.docx>"
           " <table-index> <row-index> <cell-index>"
           " <left_to_right_top_to_bottom|top_to_bottom_right_to_left|bottom_to_top_left_to_right|left_to_right_top_to_bottom_rotated|top_to_bottom_right_to_left_rotated|top_to_bottom_left_to_right_rotated>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-text-direction <input.docx>"
           " <table-index> <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-width <input.docx> <table-index>"
           " <row-index> <cell-index> <width-twips>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-width <input.docx> <table-index>"
           " <row-index> <cell-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-column-width <input.docx> <table-index>"
           " <column-index> <width-twips> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-column-width <input.docx> <table-index>"
           " <column-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-style-id <input.docx> <table-index>"
           " <style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-style-id <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-style-look <input.docx> <table-index>"
           " [--first-row <bool>] [--last-row <bool>]"
           " [--first-column <bool>] [--last-column <bool>]"
           " [--banded-rows <bool>] [--banded-columns <bool>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-style-look <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-width <input.docx> <table-index>"
           " <width-twips> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-width <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-layout-mode <input.docx> <table-index>"
           " <autofit|fixed> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-layout-mode <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-alignment <input.docx> <table-index>"
           " <left|center|right> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-alignment <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-indent <input.docx> <table-index>"
           " <indent-twips> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-indent <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-spacing <input.docx> <table-index>"
           " <spacing-twips> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-spacing <input.docx> <table-index>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-default-cell-margin <input.docx>"
           " <table-index> <top|left|bottom|right> <margin-twips>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-default-cell-margin <input.docx>"
           " <table-index> <top|left|bottom|right>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-border <input.docx> <table-index>"
           " <top|left|bottom|right|inside_horizontal|inside_vertical>"
           " --style <none|single|double_line|dashed|dotted|thick>"
           " [--size <eighth-points>] [--color <hex-or-auto>]"
           " [--space <points>] [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-border <input.docx> <table-index>"
           " <top|left|bottom|right|inside_horizontal|inside_vertical>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-margin <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right> <margin-twips>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-margin <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-cell-border <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right>"
           " --style <none|single|double_line|dashed|dotted|thick>"
           " [--size <n>] [--color <value>] [--space <n>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-cell-border <input.docx> <table-index>"
           " <row-index> <cell-index> <top|left|bottom|right>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-row-height <input.docx> <table-index>"
           " <row-index> <height-twips> <automatic|at_least|exact>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-row-height <input.docx> <table-index>"
           " <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-row-cant-split <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-row-cant-split <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-table-row-repeat-header <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli clear-table-row-repeat-header <input.docx>"
           " <table-index> <row-index> [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-runs <input.docx> <paragraph-index>"
           " [--run <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-runs <input.docx> <paragraph-index>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even] [--run <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-tables <input.docx>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--table <index>|--bookmark <name>] [--json]\n"
        << "  featherdoc_cli inspect-template-table-rows <input.docx>"
           " [<table-index>|--bookmark <name>|--after-text <text>|"
           " --header-cell <text> ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--row <index>] [--json]\n"
        << "  featherdoc_cli inspect-template-table-cells <input.docx>"
           " [<table-index>|--bookmark <name>|--after-text <text>|"
           " --header-cell <text> ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--row <index>] [--cell <index>|--grid-column <index>] [--json]\n"
        << "  featherdoc_cli set-template-table-cell-text <input.docx>"
           " (<table-index> <row-index> (<cell-index>|--grid-column <index>)|"
           " --bookmark <name> <row-index> (<cell-index>|--grid-column <index>)|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> (<cell-index>|--grid-column <index>))"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " (--text <text> | --text-file <path>)"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-table-row-texts <input.docx>"
           " (<table-index> <start-row-index>|"
           " --bookmark <name> <start-row-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <start-row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " (--row <text> [--cell <text> ...])+"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-table-cell-block-texts <input.docx>"
           " (<table-index> <start-row-index> <start-cell-index>|"
           " --bookmark <name> <start-row-index> <start-cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <start-row-index> <start-cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " (--row <text> [--cell <text> ...])+"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-table-from-json <input.docx>"
           " [<table-index>|--bookmark <name>|--after-text <text>|"
           " --header-cell <text> ...]"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " --patch-file <path> [--output <path>] [--json]\n"
        << "  featherdoc_cli set-template-tables-from-json <input.docx>"
           " --patch-file <path>"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-column-before <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-column-after <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-template-table-column <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli append-template-table-row <input.docx>"
           " (<table-index>|--bookmark <name>|"
           " --after-text <text>|--header-cell <text> ...)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--cell-count <n>] [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-row-before <input.docx>"
           " (<table-index> <row-index>|--bookmark <name> <row-index>|"
           " [--after-text <text>|--header-cell <text> ...] <row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli insert-template-table-row-after <input.docx>"
           " (<table-index> <row-index>|--bookmark <name> <row-index>|"
           " [--after-text <text>|--header-cell <text> ...] <row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli remove-template-table-row <input.docx>"
           " (<table-index> <row-index>|--bookmark <name> <row-index>|"
           " [--after-text <text>|--header-cell <text> ...] <row-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-template-table-cells <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " --direction <right|down> [--count <n>]"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli unmerge-template-table-cells <input.docx>"
           " (<table-index> <row-index> <cell-index>|"
           " --bookmark <name> <row-index> <cell-index>|"
           " [--after-text <text>|--header-cell <text> ...]"
           " <row-index> <cell-index>)"
           " [--part body|header|footer|section-header|section-footer]"
           " [--index <part-index>] [--section <section-index>]"
           " [--kind default|first|even]"
           " [--header-row <index>] [--occurrence <index>]"
           " --direction <right|down> [--output <path>] [--json]\n";
}

} // namespace featherdoc_cli
