#include "featherdoc_cli_usage.hpp"

#include "featherdoc_cli_usage_table.hpp"

#include <ostream>

namespace featherdoc_cli {

void print_usage(std::ostream &stream) {
    stream
        << "Usage:\n"
        << "  featherdoc_cli run-recipe --recipe <recipe.json>"
           " --inputs <inputs.json> --output <output-dir> [--json]\n"
        << "  featherdoc_cli export-pdf <input.docx> --output <output.pdf>"
           " [--render-headers-and-footers] [--render-inline-images]"
           " [--expand-header-footer-page-placeholders]"
           " [--font-file <path>] [--cjk-font-file <path>]"
           " [--font-map <family>=<path>]..."
           " [--title <text>] [--creator <text>] [--no-font-subset]"
           " [--no-system-font-fallbacks]"
           " [--summary-json <path>] [--json]\n"
#if defined(FEATHERDOC_CLI_ENABLE_PDF_IMPORT)
        << "  featherdoc_cli import-pdf <input.pdf> --output <output.docx>"
           " [--import-table-candidates-as-tables]"
           " [--min-table-continuation-confidence <score>]"
           " [--json]\n"
        << "    --json includes table_continuation_diagnostics for PDF table"
           " merge decisions.\n"
        << "    --min-table-continuation-confidence records"
           " min_table_continuation_confidence in JSON when set.\n"
#endif
        << "  featherdoc_cli inspect-sections <input.docx>\n"
        << "    [--json]\n"
        << "  featherdoc_cli inspect-styles <input.docx>"
           " [--style <style-id>] [--usage] [--json]\n"
        << "  featherdoc_cli inspect-style-inheritance <input.docx> <style-id>"
           " [--json]\n"
        << "  featherdoc_cli rename-style <input.docx> <old-style-id>"
           " <new-style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli merge-style <input.docx> <source-style-id>"
           " <target-style-id> [--output <path>] [--json]\n"
        << "  featherdoc_cli plan-style-refactor <input.docx>"
           " [--rename <old:new>] [--merge <source:target>]"
           " [--output-plan <path>] [--json]\n"
        << "  featherdoc_cli suggest-style-merges <input.docx>"
           " [--confidence-profile recommended|strict|review|exploratory]"
           " [--min-confidence <0-100>] [--source-style <id>]..."
           " [--target-style <id>]... [--fail-on-suggestion]"
           " [--output-plan <path>] [--json]\n"
        << "  featherdoc_cli apply-style-refactor <input.docx>"
           " [--plan-file <path> | --rename <old:new> | --merge <source:target>]"
           " [--rollback-plan <path>] [--output <path>] [--json]\n"
        << "  featherdoc_cli restore-style-merge <input.docx>"
           " --rollback-plan <path> [--entry <index>]..."
           " [--source-style <id>]... [--target-style <id>]..."
           " [--dry-run | --output <path>] [--json]\n"
        << "  featherdoc_cli plan-prune-unused-styles <input.docx>"
           " [--json]\n"
        << "  featherdoc_cli prune-unused-styles <input.docx>"
           " [--output <path>] [--json]\n"
        << "  featherdoc_cli inspect-numbering <input.docx>"
           " [--definition <id>] [--instance <num-id>] [--json]\n"
        << "  featherdoc_cli inspect-style-numbering <input.docx> [--json]\n"
        << "  featherdoc_cli audit-style-numbering <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli audit-table-style-regions <input.docx>"
           " [--style <style-id>] [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli audit-table-style-inheritance <input.docx>"
           " [--style <style-id>] [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli audit-table-style-quality <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli plan-table-style-quality-fixes <input.docx>"
           " [--fail-on-issue] [--json]\n"
        << "  featherdoc_cli apply-table-style-quality-fixes <input.docx>"
           " --look-only --output <path> [--json]\n"
        << "  featherdoc_cli repair-style-numbering <input.docx>"
           " [--catalog-file <catalog.json>] [--plan-only | --apply --output <path>] [--json]\n"
        << "  featherdoc_cli export-numbering-catalog <input.docx>"
           " [--output <catalog.json>] [--json]\n"
        << "  featherdoc_cli check-numbering-catalog <input.docx>"
           " --catalog-file <catalog.json>"
           " [--output <generated-catalog.json>] [--json]\n"
        << "  featherdoc_cli import-numbering-catalog <input.docx>"
           " --catalog-file <catalog.json> [--output <path>] [--json]\n"
        << "  featherdoc_cli patch-numbering-catalog <catalog.json>"
           " --patch-file <patch.json> [--output <catalog.json>] [--json]\n"
        << "  featherdoc_cli lint-numbering-catalog <catalog.json> [--json]\n"
        << "  featherdoc_cli diff-numbering-catalog <left-catalog.json>"
           " <right-catalog.json> [--fail-on-diff] [--json]\n"
        << "  featherdoc_cli inspect-paragraphs <input.docx>"
           " [--paragraph <index>] [--json]\n"
        << "  featherdoc_cli inspect-tables <input.docx>"
           " [--table <index>] [--json]\n"
        << "  featherdoc_cli semantic-diff <left.docx> <right.docx>"
           " [--fail-on-diff] [--index-alignment]"
           " [--alignment-cell-limit <count>]"
           " [--include-image-relationship-ids]"
           " [--include-content-control-ids] [--no-fields]"
           " [--no-styles] [--no-numbering]"
           " [--no-footnotes] [--no-endnotes] [--no-comments] [--no-revisions]"
           " [--no-template-parts] [--no-resolved-section-template-parts]"
           " [--no-sections] [--json]\n";

    print_table_usage(stream);
    #include "featherdoc_cli_usage_commands.inc"
} // namespace featherdoc_cli
