. (Join-Path $PSScriptRoot "release_blocker_metadata_core.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_visual_guidance.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_project_guidance.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_guidance_dispatch.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_source_contracts.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_normalized_items.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_checklists.ps1")
. (Join-Path $PSScriptRoot "release_blocker_metadata_markdown_sections.ps1")
