#include "document_styles_defaults_read_methods.inc"

#include "document_styles_defaults_font_write_methods.inc"

#include "document_styles_defaults_language_write_methods.inc"

#include "document_styles_defaults_direction_write_methods.inc"

#include "document_styles_defaults_font_clear_methods.inc"

#include "document_styles_defaults_language_clear_methods.inc"

#include "document_styles_defaults_direction_clear_methods.inc"