if(NOT DEFINED FEATHERDOC_PDFIUM_RUN_STEP)
    message(FATAL_ERROR "FEATHERDOC_PDFIUM_RUN_STEP is required")
endif()

if(NOT DEFINED FEATHERDOC_PDFIUM_SOURCE_DIR)
    message(FATAL_ERROR "FEATHERDOC_PDFIUM_SOURCE_DIR is required")
endif()

set(ENV{DEPOT_TOOLS_WIN_TOOLCHAIN} "0")

if(DEFINED FEATHERDOC_DEPOT_TOOLS_DIR AND NOT FEATHERDOC_DEPOT_TOOLS_DIR STREQUAL "")
    if(WIN32)
        set(ENV{PATH} "${FEATHERDOC_DEPOT_TOOLS_DIR};$ENV{PATH}")
    else()
        set(ENV{PATH} "${FEATHERDOC_DEPOT_TOOLS_DIR}:$ENV{PATH}")
    endif()
endif()

if(WIN32
        AND DEFINED FEATHERDOC_PDFIUM_VS_YEAR
        AND NOT FEATHERDOC_PDFIUM_VS_YEAR STREQUAL ""
        AND DEFINED FEATHERDOC_PDFIUM_VS_INSTALL
        AND NOT FEATHERDOC_PDFIUM_VS_INSTALL STREQUAL "")
    set("ENV{vs${FEATHERDOC_PDFIUM_VS_YEAR}_install}"
        "${FEATHERDOC_PDFIUM_VS_INSTALL}")
endif()

if(FEATHERDOC_PDFIUM_RUN_STEP STREQUAL "configure")
    execute_process(
        COMMAND "${FEATHERDOC_GN_EXECUTABLE}" gen
            "${FEATHERDOC_PDFIUM_OUT_DIR}"
            "--args=${FEATHERDOC_PDFIUM_GN_ARGS}"
        WORKING_DIRECTORY "${FEATHERDOC_PDFIUM_SOURCE_DIR}"
        RESULT_VARIABLE result)
elseif(FEATHERDOC_PDFIUM_RUN_STEP STREQUAL "build")
    execute_process(
        COMMAND "${FEATHERDOC_NINJA_EXECUTABLE}" -C
            "${FEATHERDOC_PDFIUM_OUT_DIR}"
            "${FEATHERDOC_PDFIUM_NINJA_TARGET}"
        WORKING_DIRECTORY "${FEATHERDOC_PDFIUM_SOURCE_DIR}"
        RESULT_VARIABLE result)
else()
    message(FATAL_ERROR
        "Unsupported FEATHERDOC_PDFIUM_RUN_STEP: ${FEATHERDOC_PDFIUM_RUN_STEP}")
endif()

if(NOT result EQUAL 0)
    message(FATAL_ERROR
        "PDFium ${FEATHERDOC_PDFIUM_RUN_STEP} step failed with exit code ${result}")
endif()
