# featherdoc_cli target definition and install rules.
# Kept in a module so the top-level build graph stays readable.


if(BUILD_CLI)
    add_executable(featherdoc_cli
        cli/featherdoc_cli_main.cpp
        cli/featherdoc_cli_command_support.cpp
        cli/featherdoc_cli_domain_image_parse.cpp
        cli/featherdoc_cli_domain_names.cpp
        cli/featherdoc_cli_domain_names_core.cpp
        cli/featherdoc_cli_domain_names_table.cpp
        cli/featherdoc_cli_domain_names_table_style_position.cpp
        cli/featherdoc_cli_domain_names_template_image.cpp
        cli/featherdoc_cli_domain_parse.cpp
        cli/featherdoc_cli_domain_table_border_parse.cpp
        cli/featherdoc_cli_domain_table_layout_parse.cpp
        cli/featherdoc_cli_domain_table_text_parse.cpp
        cli/featherdoc_cli_errors.cpp
        cli/featherdoc_cli_field_complex_options_parse.cpp
        cli/featherdoc_cli_field_parse.cpp
        cli/featherdoc_cli_field_append_command.cpp
        cli/featherdoc_cli_field_commands.cpp
        cli/featherdoc_cli_field_update_commands.cpp
        cli/featherdoc_cli_formatting_commands.cpp
        cli/featherdoc_cli_bookmark_commands.cpp
        cli/featherdoc_cli_bookmark_image_commands.cpp
        cli/featherdoc_cli_bookmark_inspect_commands.cpp
        cli/featherdoc_cli_bookmark_output.cpp
        cli/featherdoc_cli_bookmark_support.cpp
        cli/featherdoc_cli_bookmark_table_commands.cpp
        cli/featherdoc_cli_bookmark_text_commands.cpp
        cli/featherdoc_cli_bookmark_visibility_commands.cpp
        cli/featherdoc_cli_content_control_commands.cpp
        cli/featherdoc_cli_content_control_image_commands.cpp
        cli/featherdoc_cli_content_control_inspect_commands.cpp
        cli/featherdoc_cli_content_control_mutation_output.cpp
        cli/featherdoc_cli_content_control_output.cpp
        cli/featherdoc_cli_content_control_paragraph_commands.cpp
        cli/featherdoc_cli_content_control_sync_commands.cpp
        cli/featherdoc_cli_content_control_table_commands.cpp
        cli/featherdoc_cli_content_control_text_commands.cpp
        cli/featherdoc_cli_content_control_form_state_options_parse.cpp
        cli/featherdoc_cli_content_control_form_state_options_parse_state.cpp
        cli/featherdoc_cli_content_control_form_state_options_parse_support.cpp
        cli/featherdoc_cli_content_control_inspect_options_parse.cpp
        cli/featherdoc_cli_content_control_options_parse_support.cpp
        cli/featherdoc_cli_content_control_rich_options_parse.cpp
        cli/featherdoc_cli_content_control_sync_options_parse.cpp
        cli/featherdoc_cli_content_control_text_options_parse.cpp
        cli/featherdoc_cli_default_run_properties_commands.cpp
        cli/featherdoc_cli_image_append_options_parse.cpp
        cli/featherdoc_cli_image_append_options_parse_crop.cpp
        cli/featherdoc_cli_image_append_options_parse_floating_flag.cpp
        cli/featherdoc_cli_image_append_options_parse_floating_layout.cpp
        cli/featherdoc_cli_image_append_options_parse_floating_support.cpp
        cli/featherdoc_cli_image_append_options_parse_support.cpp
        cli/featherdoc_cli_image_commands.cpp
        cli/featherdoc_cli_inspect_content_options_parse.cpp
        cli/featherdoc_cli_image_output.cpp
        cli/featherdoc_cli_image_options_parse.cpp
        cli/featherdoc_cli_bookmark_image_options_parse.cpp
        cli/featherdoc_cli_bookmark_block_options_parse.cpp
        cli/featherdoc_cli_bookmark_paragraph_replace_options_parse.cpp
        cli/featherdoc_cli_bookmark_table_options_parse.cpp
        cli/featherdoc_cli_bookmark_text_fill_options_parse.cpp
        cli/featherdoc_cli_bookmark_text_inspect_options_parse.cpp
        cli/featherdoc_cli_bookmark_text_options_parse_support.cpp
        cli/featherdoc_cli_bookmark_text_replace_options_parse.cpp
        cli/featherdoc_cli_bookmark_visibility_apply_options_parse.cpp
        cli/featherdoc_cli_bookmark_visibility_set_options_parse.cpp
        cli/featherdoc_cli_document_content_commands.cpp
        cli/featherdoc_cli_document_mutation_options_parse.cpp
        cli/featherdoc_cli_document_revision_options_parse.cpp
        cli/featherdoc_cli_document_review_comment_metadata_options_parse.cpp
        cli/featherdoc_cli_document_review_comment_options_parse.cpp
        cli/featherdoc_cli_document_review_options_parse.cpp
        cli/featherdoc_cli_document_rich_content_options_parse.cpp
        cli/featherdoc_cli_inspect_numbering_options_parse.cpp
        cli/featherdoc_cli_inspect_style_options_parse.cpp
        cli/featherdoc_cli_inspect_table_item_options_parse.cpp
        cli/featherdoc_cli_json.cpp
        cli/featherdoc_cli_json_parse.cpp
        cli/featherdoc_cli_json_parse_members.cpp
        cli/featherdoc_cli_json_parse_string.cpp
        cli/featherdoc_cli_json_parse_value.cpp
        cli/featherdoc_cli_numbering_catalog_diff.cpp
        cli/featherdoc_cli_numbering_catalog_lint.cpp
        cli/featherdoc_cli_numbering_catalog_options_parse.cpp
        cli/featherdoc_cli_numbering_catalog_diff_output.cpp
        cli/featherdoc_cli_numbering_catalog_output.cpp
        cli/featherdoc_cli_numbering_catalog_output_json.cpp
        cli/featherdoc_cli_numbering_catalog_definition_parse.cpp
        cli/featherdoc_cli_numbering_catalog_instance_parse.cpp
        cli/featherdoc_cli_numbering_catalog_level_override_parse.cpp
        cli/featherdoc_cli_numbering_catalog_level_parse.cpp
        cli/featherdoc_cli_numbering_catalog_parse.cpp
        cli/featherdoc_cli_numbering_catalog_parse_support.cpp
        cli/featherdoc_cli_numbering_catalog_patch_apply.cpp
        cli/featherdoc_cli_numbering_catalog_patch_level_parse.cpp
        cli/featherdoc_cli_numbering_catalog_patch_override_entry_parse.cpp
        cli/featherdoc_cli_numbering_catalog_patch_override_parse.cpp
        cli/featherdoc_cli_numbering_catalog_patch_parse.cpp
        cli/featherdoc_cli_numbering_catalog_patch_parse_support.cpp
        cli/featherdoc_cli_numbering_catalog_commands.cpp
        cli/featherdoc_cli_numbering_definition_options_parse.cpp
        cli/featherdoc_cli_numbering_level_options_parse.cpp
        cli/featherdoc_cli_numbering_inspect_commands.cpp
        cli/featherdoc_cli_numbering_json.cpp
        cli/featherdoc_cli_page_setup.cpp
        cli/featherdoc_cli_page_setup_commands.cpp
        cli/featherdoc_cli_page_setup_parse.cpp
        cli/featherdoc_cli_paragraph_inspect_body_commands.cpp
        cli/featherdoc_cli_paragraph_inspect_commands.cpp
        cli/featherdoc_cli_paragraph_inspect_load.cpp
        cli/featherdoc_cli_paragraph_inspect_output.cpp
        cli/featherdoc_cli_paragraph_style_properties_options_parse.cpp
        cli/featherdoc_cli_template_paragraph_inspect_commands.cpp
        cli/featherdoc_cli_template_paragraph_inspect_paragraph_commands.cpp
        cli/featherdoc_cli_template_paragraph_inspect_paragraph_output.cpp
        cli/featherdoc_cli_template_paragraph_inspect_run_commands.cpp
        cli/featherdoc_cli_template_paragraph_inspect_run_output.cpp
        cli/featherdoc_cli_paragraph_numbering_commands.cpp
        cli/featherdoc_cli_paragraph_numbering_options_parse.cpp
        cli/featherdoc_cli_paragraph_list_options_parse.cpp
        cli/featherdoc_cli_paragraph_style_numbering_options_parse.cpp
        cli/featherdoc_cli_paragraph_run_commands_support.cpp
        cli/featherdoc_cli_paragraph_run_commands.cpp
        cli/featherdoc_cli_paragraph_numbering_commands_support.cpp
        cli/featherdoc_cli_paragraph_numbering_definition_commands.cpp
        cli/featherdoc_cli_paragraph_numbering_list_commands.cpp
        cli/featherdoc_cli_paragraph_numbering_style_commands.cpp
        cli/featherdoc_cli_paragraph_run_font_family_commands.cpp
        cli/featherdoc_cli_paragraph_run_language_commands.cpp
        cli/featherdoc_cli_paragraph_run_style_commands.cpp
        cli/featherdoc_cli_paragraph_run_options_parse.cpp
        cli/featherdoc_cli_run_style_properties_commands.cpp
        cli/featherdoc_cli_run_style_properties_support.cpp
        cli/featherdoc_cli_section_management_commands.cpp
        cli/featherdoc_cli_section_part_commands.cpp
        cli/featherdoc_cli_section_part_management_commands.cpp
        cli/featherdoc_cli_section_part_reference_commands.cpp
        cli/featherdoc_cli_section_part_support.cpp
        cli/featherdoc_cli_semantic_diff.cpp
        cli/featherdoc_cli_semantic_diff_output.cpp
        cli/featherdoc_cli_semantic_diff_options_parse.cpp
        cli/featherdoc_cli_style_ensure_commands.cpp
        cli/featherdoc_cli_style_ensure_common_options_parse.cpp
        cli/featherdoc_cli_style_ensure_options_parse.cpp
        cli/featherdoc_cli_style_ensure_table_options_parse.cpp
        cli/featherdoc_cli_style_ensure_table_region_basic_parse.cpp
        cli/featherdoc_cli_style_ensure_table_region_box_parse.cpp
        cli/featherdoc_cli_style_ensure_table_region_paragraph_parse.cpp
        cli/featherdoc_cli_style_ensure_table_region_parse_support.cpp
        cli/featherdoc_cli_style_inspect_commands.cpp
        cli/featherdoc_cli_append_table_row_options_parse.cpp
        cli/featherdoc_cli_table_border_margin_commands.cpp
        cli/featherdoc_cli_table_border_margin_default_margin_commands.cpp
        cli/featherdoc_cli_table_border_margin_table_border_commands.cpp
        cli/featherdoc_cli_table_border_margin_cell_margin_commands.cpp
        cli/featherdoc_cli_table_border_margin_cell_border_commands.cpp
        cli/featherdoc_cli_table_cell_merge_options_parse.cpp
        cli/featherdoc_cli_table_cell_style_options_parse.cpp
        cli/featherdoc_cli_table_cell_style_commands.cpp
        cli/featherdoc_cli_table_cell_style_fill_commands.cpp
        cli/featherdoc_cli_table_cell_style_support.cpp
        cli/featherdoc_cli_table_cell_style_text_direction_commands.cpp
        cli/featherdoc_cli_table_cell_style_vertical_alignment_commands.cpp
        cli/featherdoc_cli_table_cell_style_width_commands.cpp
        cli/featherdoc_cli_table_commands.cpp
        cli/featherdoc_cli_table_column_commands.cpp
        cli/featherdoc_cli_table_column_insert_commands.cpp
        cli/featherdoc_cli_table_column_support.cpp
        cli/featherdoc_cli_table_format_commands.cpp
        cli/featherdoc_cli_table_format_support.cpp
        cli/featherdoc_cli_table_inspect_commands.cpp
        cli/featherdoc_cli_table_inspect_output.cpp
        cli/featherdoc_cli_table_inspect_output_json.cpp
        cli/featherdoc_cli_table_inspect_output_text.cpp
        cli/featherdoc_cli_table_merge_commands.cpp
        cli/featherdoc_cli_table_row_height_commands.cpp
        cli/featherdoc_cli_table_row_commands.cpp
        cli/featherdoc_cli_table_row_summary.cpp
        cli/featherdoc_cli_table_row_support.cpp
        cli/featherdoc_cli_table_cell_text_options_parse.cpp
        cli/featherdoc_cli_table_column_width_commands.cpp
        cli/featherdoc_cli_table_insert_remove_commands.cpp
        cli/featherdoc_cli_table_row_toggle_commands.cpp
        cli/featherdoc_cli_table_structure_commands.cpp
        cli/featherdoc_cli_table_structure_support.cpp
        cli/featherdoc_cli_table_structure_validation.cpp
        cli/featherdoc_cli_table_style_commands.cpp
        cli/featherdoc_cli_table_style_audit_output.cpp
        cli/featherdoc_cli_table_style_audit_output_json.cpp
        cli/featherdoc_cli_table_style_output.cpp
        cli/featherdoc_cli_table_text_commands.cpp
        cli/featherdoc_cli_template_inspect_options_parse.cpp
        cli/featherdoc_cli_template_table_inspect_table_cells_options_parse.cpp
        cli/featherdoc_cli_template_table_inspect_table_rows_options_parse.cpp
        cli/featherdoc_cli_template_table_inspect_tables_options_parse.cpp
        cli/featherdoc_cli_template_table_selector_options_parse.cpp
        cli/featherdoc_cli_template_part_selection.cpp
        cli/featherdoc_cli_template_table_commands.cpp
        cli/featherdoc_cli_template_table_inspect_commands_detail.cpp
        cli/featherdoc_cli_template_table_inspect_tables_command.cpp
        cli/featherdoc_cli_template_table_inspect_rows_command.cpp
        cli/featherdoc_cli_template_table_inspect_cells_command.cpp
        cli/featherdoc_cli_template_table_inspect_output.cpp
        cli/featherdoc_cli_template_table_json_batch_operation_finalize.cpp
        cli/featherdoc_cli_template_table_json_batch_operation_member_parse.cpp
        cli/featherdoc_cli_template_table_json_batch_operation_parse.cpp
        cli/featherdoc_cli_template_table_json_batch_parse.cpp
        cli/featherdoc_cli_template_table_json_patch_apply.cpp
        cli/featherdoc_cli_template_table_json_patch_commands.cpp
        cli/featherdoc_cli_template_table_json_patch_parse.cpp
        cli/featherdoc_cli_template_table_json_patch_parse_detail.cpp
        cli/featherdoc_cli_template_table_json_patch_parse_values.cpp
        cli/featherdoc_cli_template_table_column_commands_detail.cpp
        cli/featherdoc_cli_template_table_column_insert_before_command.cpp
        cli/featherdoc_cli_template_table_column_insert_after_command.cpp
        cli/featherdoc_cli_template_table_column_remove_command.cpp
        cli/featherdoc_cli_template_table_merge_commands.cpp
        cli/featherdoc_cli_template_table_merge_mutation_options_parse.cpp
        cli/featherdoc_cli_template_table_json_options_parse.cpp
        cli/featherdoc_cli_template_table_row_target_options_parse.cpp
        cli/featherdoc_cli_template_table_cell_target_options_parse.cpp
        cli/featherdoc_cli_template_table_optional_cell_target_options_parse.cpp
        cli/featherdoc_cli_template_table_target_options_parse.cpp
        cli/featherdoc_cli_template_table_output.cpp
        cli/featherdoc_cli_template_table_mutation_options_parse.cpp
        cli/featherdoc_cli_template_table_row_mutation_options_parse.cpp
        cli/featherdoc_cli_template_table_resolve.cpp
        cli/featherdoc_cli_template_table_cell_text_command.cpp
        cli/featherdoc_cli_template_table_row_commands_detail.cpp
        cli/featherdoc_cli_template_table_row_append_command.cpp
        cli/featherdoc_cli_template_table_row_insert_before_command.cpp
        cli/featherdoc_cli_template_table_row_insert_after_command.cpp
        cli/featherdoc_cli_template_table_row_remove_command.cpp
        cli/featherdoc_cli_template_table_text_commands.cpp
        cli/featherdoc_cli_template_table_text_support.cpp
        cli/featherdoc_cli_template_validation_schema_options_parse.cpp
        cli/featherdoc_cli_template_validation_options_parse.cpp
        cli/featherdoc_cli_inspect_style_audit_options_parse.cpp
        cli/featherdoc_cli_inspect_style_quality_fixes_options_parse.cpp
        cli/featherdoc_cli_inspect_style_repair_numbering_options_parse.cpp
        cli/featherdoc_cli_run_properties_clear_options_parse.cpp
        cli/featherdoc_cli_run_properties_common_options_parse.cpp
        cli/featherdoc_cli_run_properties_mutation_options_parse.cpp
        cli/featherdoc_cli_run_properties_options_parse.cpp
        cli/featherdoc_cli_parse.cpp
        cli/featherdoc_cli_pdf_commands.cpp
        cli/featherdoc_cli_pdf_export_commands.cpp
        cli/featherdoc_cli_pdf_export_output.cpp
        cli/featherdoc_cli_pdf_import_commands.cpp
        cli/featherdoc_cli_pdf_import_output.cpp
        cli/featherdoc_cli_pdf_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_build_request_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_build_request_operation_finalize.cpp
        cli/featherdoc_cli_review_mutation_plan_build_request_operation_member_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_build_request_operation_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_build_request_parse_support.cpp
        cli/featherdoc_cli_review_mutation_plan_kind_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_operation_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_parse.cpp
        cli/featherdoc_cli_review_mutation_plan_write.cpp
        cli/featherdoc_cli_run_recipe_batch_replace.cpp
        cli/featherdoc_cli_run_recipe_commands.cpp
        cli/featherdoc_cli_run_recipe_execute.cpp
        cli/featherdoc_cli_run_recipe_inputs_parse.cpp
        cli/featherdoc_cli_run_recipe_options_parse.cpp
        cli/featherdoc_cli_run_recipe_parse_support.cpp
        cli/featherdoc_cli_run_recipe_recipe_id_parse.cpp
        cli/featherdoc_cli_section_options_parse.cpp
        cli/featherdoc_cli_style_options_parse.cpp
        cli/featherdoc_cli_style_output.cpp
        cli/featherdoc_cli_style_refactor_apply_commands.cpp
        cli/featherdoc_cli_style_refactor_commands.cpp
        cli/featherdoc_cli_style_refactor_direct_commands.cpp
        cli/featherdoc_cli_style_refactor_plan_commands.cpp
        cli/featherdoc_cli_style_refactor_restore_commands.cpp
        cli/featherdoc_cli_style_merge_restore_options_parse.cpp
        cli/featherdoc_cli_style_merge_suggestion_options_parse.cpp
        cli/featherdoc_cli_style_refactor_apply_options_parse.cpp
        cli/featherdoc_cli_style_refactor_output.cpp
        cli/featherdoc_cli_style_refactor_pair_parse.cpp
        cli/featherdoc_cli_style_refactor_plan.cpp
        cli/featherdoc_cli_style_refactor_plan_file_parse.cpp
        cli/featherdoc_cli_style_refactor_plan_operations_parse.cpp
        cli/featherdoc_cli_style_refactor_plan_options_parse.cpp
        cli/featherdoc_cli_style_refactor_plan_parse.cpp
        cli/featherdoc_cli_style_refactor_restore_output.cpp
        cli/featherdoc_cli_style_refactor_rollback_parse.cpp
        cli/featherdoc_cli_style_numbering_commands.cpp
        cli/featherdoc_cli_style_numbering_audit.cpp
        cli/featherdoc_cli_style_numbering_audit_support.cpp
        cli/featherdoc_cli_style_numbering_output.cpp
        cli/featherdoc_cli_style_numbering_repair_suggestions.cpp
        cli/featherdoc_cli_table_style_look_options_parse.cpp
        cli/featherdoc_cli_table_position_plan_build.cpp
        cli/featherdoc_cli_table_position_commands.cpp
        cli/featherdoc_cli_table_position_options_parse.cpp
        cli/featherdoc_cli_table_position_options_parse_support.cpp
        cli/featherdoc_cli_table_position_output.cpp
        cli/featherdoc_cli_table_position_plan_options_parse.cpp
        cli/featherdoc_cli_table_position_plan_parse.cpp
        cli/featherdoc_cli_table_position_set_anchor_options_parse.cpp
        cli/featherdoc_cli_table_position_set_options_parse.cpp
        cli/featherdoc_cli_table_position_set_preset_defaults.cpp
        cli/featherdoc_cli_table_position_set_spacing_options_parse.cpp
        cli/featherdoc_cli_table_position_commands_plan.cpp
        cli/featherdoc_cli_table_position_commands_mutate.cpp
        cli/featherdoc_cli_table_position_commands_support.cpp
        cli/featherdoc_cli_review_commands.cpp
        cli/featherdoc_cli_review_comment_commands.cpp
        cli/featherdoc_cli_review_comment_range_commands.cpp
        cli/featherdoc_cli_review_comment_thread_commands.cpp
        cli/featherdoc_cli_review_mutation_plan.cpp
        cli/featherdoc_cli_review_mutation_plan_apply.cpp
        cli/featherdoc_cli_review_mutation_plan_build.cpp
        cli/featherdoc_cli_review_mutation_plan_commands.cpp
        cli/featherdoc_cli_review_mutation_plan_preview.cpp
        cli/featherdoc_cli_review_mutation_plan_ranges.cpp
        cli/featherdoc_cli_review_output.cpp
        cli/featherdoc_cli_review_output_inspect.cpp
        cli/featherdoc_cli_review_output_mutation_plan.cpp
        cli/featherdoc_cli_review_output_text_range.cpp
        cli/featherdoc_cli_review_revision_commands.cpp
        cli/featherdoc_cli_template_schema_convert.cpp
        cli/featherdoc_cli_template_schema_export.cpp
        cli/featherdoc_cli_template_schema_ops.cpp
        cli/featherdoc_cli_template_schema_commands.cpp
        cli/featherdoc_cli_template_schema_diff_output.cpp
        cli/featherdoc_cli_template_schema_diff_options_parse.cpp
        cli/featherdoc_cli_template_schema_export_check_options_parse.cpp
        cli/featherdoc_cli_template_schema_export_summary.cpp
        cli/featherdoc_cli_template_schema_lint_summary.cpp
        cli/featherdoc_cli_template_schema_maintenance_options_parse.cpp
        cli/featherdoc_cli_template_schema_mutation_summary.cpp
        cli/featherdoc_cli_template_schema_options_parse_support.cpp
        cli/featherdoc_cli_template_schema_patch_options_parse.cpp
        cli/featherdoc_cli_template_schema_output.cpp
        cli/featherdoc_cli_template_schema_output_files.cpp
        cli/featherdoc_cli_template_schema_patch_summary.cpp
        cli/featherdoc_cli_template_schema_patch_output.cpp
        cli/featherdoc_cli_template_schema_patch_ops.cpp
        cli/featherdoc_cli_template_schema_patch_apply_ops.cpp
        cli/featherdoc_cli_template_schema_patch_diff_ops.cpp
        cli/featherdoc_cli_template_schema_patch_repair_ops.cpp
        cli/featherdoc_cli_template_schema_patch_parse.cpp
        cli/featherdoc_cli_template_schema_patch_parse_detail.cpp
        cli/featherdoc_cli_template_schema_patch_parse_target_selector.cpp
        cli/featherdoc_cli_template_schema_patch_parse_target_selectors_array.cpp
        cli/featherdoc_cli_template_schema_patch_parse_rename_slot_finalize.cpp
        cli/featherdoc_cli_template_schema_patch_parse_rename_slot_member.cpp
        cli/featherdoc_cli_template_schema_patch_parse_rename_slot_members.cpp
        cli/featherdoc_cli_template_schema_patch_parse_rename_slot.cpp
        cli/featherdoc_cli_template_schema_patch_parse_remove_slot_finalize.cpp
        cli/featherdoc_cli_template_schema_patch_parse_remove_slot_member.cpp
        cli/featherdoc_cli_template_schema_patch_parse_remove_slot_members.cpp
        cli/featherdoc_cli_template_schema_patch_parse_remove_slot.cpp
        cli/featherdoc_cli_template_schema_patch_parse_slot_mutation.cpp
        cli/featherdoc_cli_template_schema_patch_parse_update_slot_finalize.cpp
        cli/featherdoc_cli_template_schema_patch_parse_update_slot_finalize_detail.cpp
        cli/featherdoc_cli_template_schema_patch_parse_update_slot_member.cpp
        cli/featherdoc_cli_template_schema_patch_parse_update_slot_member_helpers.cpp
        cli/featherdoc_cli_template_schema_parse.cpp
        cli/featherdoc_cli_template_schema_parse_target.cpp
        cli/featherdoc_cli_template_schema_parse_target_member.cpp
        cli/featherdoc_cli_template_schema_slot_parse_finalize.cpp
        cli/featherdoc_cli_template_schema_slot_parse_member.cpp
        cli/featherdoc_cli_template_schema_slot_parse.cpp
        cli/featherdoc_cli_template_schema_target_output.cpp
        cli/featherdoc_cli_template_schema_validation_output.cpp
        cli/featherdoc_cli_template_slot_parse.cpp
        cli/featherdoc_cli_text.cpp
        cli/featherdoc_cli_usage.cpp
        cli/featherdoc_cli_usage_table.cpp
        cli/featherdoc_cli_validation_part.cpp
        cli/featherdoc_cli_dispatch.cpp
        cli/featherdoc_cli.cpp)
    target_link_libraries(featherdoc_cli PRIVATE FeatherDoc::FeatherDoc)
    if(FEATHERDOC_BUILD_PDF AND TARGET FeatherDocPdf)
        target_compile_definitions(featherdoc_cli PRIVATE FEATHERDOC_CLI_ENABLE_PDF=1)
        target_link_libraries(featherdoc_cli PRIVATE FeatherDoc::Pdf)
    endif()
    if(FEATHERDOC_BUILD_PDF_IMPORT AND TARGET FeatherDocPdfImport)
        target_compile_definitions(
            featherdoc_cli PRIVATE FEATHERDOC_CLI_ENABLE_PDF_IMPORT=1)
        target_link_libraries(featherdoc_cli PRIVATE FeatherDoc::PdfImport)
    endif()
    featherdoc_copy_runtime_dlls(featherdoc_cli)

    install(
        TARGETS featherdoc_cli
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    )
endif()
